export const brownies = {
  name: 'Brownies',
  param: 'brownies',
  recipeImage: 'assets/images/brownies.jpg',
  star: false,
  introText: 'Rich, fudgy brownies with a hint of syrup and optional dark chocolate.',
  description:
    'These brownies are simple, moist, and chocolatey, with a touch of flavored syrup for extra depth. Add dark chocolate for even more decadence.',
  category: 'dessert',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Butter',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 120,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 180,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flour',
      amount: 120,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cocoa powder',
      amount: 40,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flavored syrup',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark chocolate (+70%)',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat oven to 175°C (350°F). Grease and line a baking pan.',
    'Melt the butter in a saucepan or microwave. Let cool slightly.',
    'In a bowl, add the flour, sugar, cocoa powder, and salt. Whisk until combined to avoid lumps.',
    'Melt the butter in a saucepan over low heat, then take it off the heat and add chocolate. When melted, stir in the milk and the flavored syrup.',
    'Add the wet ingredients to the dry ingredients and mix until just combined.',
    'Pour the batter into the prepared pan or ramekins.',
    'Bake for 25 minutes.',
    'Let cool before slicing and serving.',
  ],
  notes:
    'Try different flavored syrups (e.g., vanilla, coffee, caramel) for variety. For extra fudgy brownies, slightly underbake and chill before serving.',
};
