export const chiliOilNoodles = {
  name: 'Chili Oil Noodles',
  param: 'chili-oil-noodles',
  recipeImage: 'assets/images/chili-oil-noodles.jpg',
  star: false,
  introText: 'Transform your noodles into a fiery, flavor-packed dish with this quick and easy recipe.',
  description:
    'This recipe is perfect for spice lovers who crave bold flavors in a matter of minutes. With a combination of chili flakes, soy sauces, and aromatic garlic and ginger, these noodles deliver a punch of umami and heat. Customize it with toppings like scallions or sesame seeds for a dish that’s uniquely yours.',
  category: ['main'],
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Ramen noodles',
      amount: 2,
      unit: 'servings',
      flex: 'Any noodles',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Oil',
      amount: 0.25,
      unit: 'cup',
      flex: 'Any vegetable oil',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 0.125,
      unit: 'cup',
      flex: 'Any chili flakes, fresh chili, crispy chili oil, or even hot sauce',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 0.125,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 0.125,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black vinegar',
      amount: 0.125,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tsp',
      flex: 'Any sugar or sweetener',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Roasted onion',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Scallion',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Szechuan oil',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cook the noodles according to the package instructions. Drain and set aside.',
    'In a small saucepan, heat the oil over high heat.',
    'In a large mixing bowl, combine the chili flakes, chopped garlic, ginger, sesame seeds, roasted onions, and MSG.',
    'When the oil is hot, around 180 degrees celsius or smoking, pour the oil into the bowl over the ingredients.',
    'Add the light soy, black vinegar, vinegar, szechuan oil, sesame oil, and sliced scallions, then mix.',
    'Add the cooked noodles to the bowl and toss until the noodles are evenly coated with the sauce.',
    'Garnish with more scallions and sesame seeds, if desired, before serving.',
  ],
  notes:
    'For a milder version, reduce the amount of chili flakes or substitute with a less spicy chili powder. Add your favorite vegetables or plant-based proteins for a heartier meal. This dish is highly adaptable and can be made as spicy or savory as you like!',
};
