export const chocolateMuffins = {
  name: 'Chocolate Muffins',
  param: 'chocolate-muffins',
  recipeImage: 'assets/images/chocolate-muffins.jpg',
  star: false,
  introText: 'Rich, moist chocolate muffins with cocoa and a hint of coffee.',
  description:
    'Deeply chocolatey muffins that stay moist and tender thanks to oil and yogurt. Cocoa powder and a touch of coffee intensify the chocolate flavor, while vanilla rounds everything out. Perfect for breakfast or an afternoon treat.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 120,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cocoa powder',
      amount: 40,
      unit: 'g',
      flex: 'Unsweetened natural or Dutch-process cocoa both work.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 70,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yogurt',
      amount: 50,
      unit: 'g',
      flex: 'Milk, buttermilk, or a puréed fruit like banana or applesauce.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any light-colored vinegar like rice or apple cider vinegar works well.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vanilla',
      amount: 1,
      unit: 'tsp',
      flex: 'Vanilla extract or paste.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Coffee',
      amount: 1,
      unit: 'tsp',
      flex: 'Instant espresso powder or instant coffee granules.',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, cocoa powder, baking powder, baking soda, salt, and the white sugar. Mix it with a balloon whisk to prevent any lumps forming.',
    'In a separate bowl, combine the yogurt, brown sugar, oil, milk, vanilla, and coffee. Whisk until smooth (no worries if there are some brown sugar lumps).',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 18 minutes if using small muffin ramekins, 20-23 min if using large muffin ramekins, or until a toothpick inserted into the center comes out clean.',
    'Allow the muffins to cool in the tin for 20 minutes before serving.',
  ],
  notes:
    'Store airtight at room temperature for up to 3 days or refrigerate for longer freshness. Can be frozen. Optionally fold in 80–120 g chocolate chips. For stronger chocolate flavor, bloom the coffee in the milk briefly warmed.',
};
