export const danDanNoodles = {
  name: 'Dan Dan Noodles',
  param: 'dan-dan-noodles',
  recipeImage: 'assets/images/dan-dan-noodles.jpg', // Update with actual image if available
  star: false,
  introText: 'A spicy, savory noodle dish with a rich, nutty sauce and plenty of texture.',
  description:
    'Dan Dan Noodles are a classic Sichuan street food, featuring noodles tossed in a bold, spicy sauce with soy mince, edamame, and crunchy peanuts. This version is plant-based and packed with flavor.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: true,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Noodles',
      amount: 2,
      unit: 'servings',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Soy mince',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Edamame beans',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallions',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Galbi sauce',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chinese five spice',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark soy sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Shaoxing wine',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili oil',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tahini',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Pak choi',
      amount: 2,
      unit: 'heads',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Peanuts',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Szechuan oil',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cook the noodles according to package instructions. Reserve some pasta water.',
    'In a pan, fry the soy mince, garlic, and edamame beans until fragrant and lightly browned.',
    'Add galbi sauce, Chinese five spice, light soy, dark soy, Shaoxing wine, sugar, chili oil, tahini, and (if using) Szechuan oil to the pan. Mix well.',
    'Add a splash of reserved pasta water to loosen the sauce as needed.',
    'Toss the cooked noodles in the sauce until well coated.',
    'Serve topped with fresh scallions, pak choi, and chopped peanuts.',
  ],
  notes:
    'For extra heat, add more chili oil or Szechuan oil. You can blanch the pak choi with the noodles for convenience. Adjust sauce consistency with more pasta water if needed.',
};
