export const frijolesRefritos = {
  name: 'Frijoles Refritos',
  param: 'frijoles-refritos',
  recipeImage: 'assets/images/frijoles-refritos.jpg',
  star: false,
  introText: 'Classic Mexican 🇲🇽 refried beans with serrano chili.',
  description:
    'Simple, hearty refried beans made with just a handful of ingredients. Beans are fried with onion and a whole dried serrano chili in plenty of oil, then smashed to a creamy, flavorful side dish. The serrano is left whole and meant to be eaten alongside the beans.',
  category: 'sides',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Black beans in aquafaba',
      amount: 230,
      unit: 'g',
      flex: 'White beans.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dried serrano',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Heat a generous amount of vegetable oil in a skillet over medium heat.',
    'Add the diced onion and the whole dried serrano chili.',
    'Fry for several minutes until the onion is soft and golden.',
    'Add the beans and the salt. Discard most of the aquafaba.',
    'Smash the beans with a fork or potato masher to your desired consistency.',
    'Cook, stirring occasionally, until thickened and creamy.',
    'Serve with the whole serrano chili on top — it is meant to be eaten.',
  ],
  notes:
    'Use plenty of oil for the best flavor and texture. The dried serrano should be kept whole throughout cooking. Serve as a side with chilaquiles, taquitos, rice, or alongside tortillas.',
};
