export const gochujangPasta = {
  name: 'Gochujang Pasta',
  param: 'gochujang-pasta',
  recipeImage: 'assets/images/gochujang-pasta.jpg',
  star: false,
  introText: 'A fusion dish combining Korean gochujang with creamy Italian pasta for a spicy, umami-rich meal.',
  description:
    'This Gochujang Pasta brings together the best of Korean and Italian cuisines. The fermented heat of gochujang pepper paste is balanced with rich cream and savory soy sauce, creating a silky sauce that clings perfectly to pasta. Quick to prepare and packed with bold flavors, this dish is perfect for weeknight dinners when you want something exciting with minimal effort.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Pasta',
      amount: 75,
      unit: 'g',
      flex: 'Any pasta shape works - spaghetti, fettuccine, or penne are all good options.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gochujang',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 0.5,
      unit: 'cup',
      flex: 'Any cream works',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 2,
      unit: 'tbsp',
      flex: '0.5 tsp salt.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Spring onion',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Butter',
      amount: 1,
      unit: 'tbsp',
      flex: 'Vegetable oil.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tsp',
      flex: 'Any sweetener works, like agave or maple syrup.',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Bring a pot of salted water to a boil and cook pasta until al dente.',
    'Finely chop both garlic and spring onion, keeping them separate.',
    'In a large skillet, melt the butter over medium heat. Add the garlic, cooking until fragrant, about 1-2 minutes.',
    'Reduce heat to medium-low and add the gochujang paste, cream, and light soy, stirring well to incorporate the gochujang into a smooth sauce. Add sugar if using.',
    'Simmer gently for 2-3 minutes until the sauce begins to thicken slightly.',
    'Add the drained pasta to the sauce, along with a splash of pasta water. If the sauce is too thick, add more pasta water a tablespoon at a time until you reach your desired consistency.',
    'Remove from heat and mix in the spring onion.',
  ],
  notes:
    'For extra protein, add tofu or a plant-based meat alternative. You can also toss in vegetables like spinach, mushrooms, or bok choy. The sauce will thicken as it sits, so eat immediately for best results or thin with a splash of water when reheating. This dish has a good kick of heat - adjust the gochujang amount to your spice preference.',
};
