export const sesameGingerDressing = {
  name: 'Sesame Ginger Dressing',
  param: 'sesame-ginger-dressing',
  recipeImage: 'assets/images/sesame-ginger-dressing.jpg',
  star: false,
  introText: 'A sweet and savory Asian-inspired dressing with bold sesame and ginger flavors.',
  description:
    'This aromatic sesame ginger dressing brings together the nutty richness of sesame oil with the warming spice of fresh ginger. Balanced with soy sauce, rice vinegar, and a touch of sweetness, it\'s perfect for Asian salads, slaws, or as a marinade for vegetables.',
  category: 'condiment',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Sesame oil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 0.25,
      unit: 'cup',
      flex: 'Any sweetener will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rice vinegar',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 0.125,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Finely mince or grate the ginger to avoid any large pieces.',
    'In a bowl, whisk together sesame oil, vegetable oil, and sugar until sugar dissolves.',
    'Add soy sauce, rice vinegar, and minced ginger, whisking until well combined.',
    'Taste and adjust seasoning with more sugar, soy sauce, or vinegar as needed.',
  ],
  notes: 'For a smoother texture, strain out the ginger pieces after letting the dressing sit for 30 minutes. Store in refrigerator for up to 2 weeks. Shake or stir before using as ingredients may separate.',
};
