export const sesameGingerDressing = {
  name: 'Sesame Ginger Dressing',
  param: 'sesame-ginger-dressing',
  recipeImage: '../assets/images/sesame-ginger-dressing.jpg',
  star: false,
  introText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.',
  description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Sesame oil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 0.25,
      unit: 'cup',
      flex: 'Any sweetener will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rice vinegar',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 0.125,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  ],
  notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
};
