export const stroganoff = {
  name: 'Stroganoff',
  param: 'stroganoff',
  recipeImage: 'assets/images/stroganoff.jpg',
  star: false,
  introText: 'Creamy, tangy stroganoff with plant-based sausage, onions, and warm spices served over rice.',
  description:
    'A quick, weeknight-friendly stroganoff built on savory plant-based sausage, sweet onions, oregano, and a creamy tomato base. White pepper adds gentle heat, a splash of vinegar brightens, and optional Dijon deepens the flavor. Serve it over rice for a cozy, satisfying main.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: 1,
      unit: 'serving',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Plant-based sausage',
      amount: 200,
      unit: 'g',
      flex: 'Any plant-based sausage, tofu, mushroom.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Black pepper.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato paste',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ketchup',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any vinegar.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dijon mustard',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Oregano',
      amount: 2,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cook the rice according to package directions so it’s ready when the stroganoff finishes.',
    'Chop the onion. Slice the plant-based sausage into bite-sized pieces.',
    'Place a large skillet over medium-high heat. Add the plant-based sausage and cook 3–5 minutes until browned. Add the onion and a pinch of salt and cook 3–4 minutes until softened.',
    'Sprinkle in oregano and white pepper; cook 30 seconds until fragrant.',
    'Add tomato paste and ketchup; cook 1–2 minutes, stirring, to caramelize slightly.',
    'Stir in vinegar and sugar to deglaze. Reduce heat to medium-low.',
    'Pour in the cream and stir until smooth. Add salt to taste and simmer gently 2–4 minutes until thick and glossy. Stir in Dijon if using and adjust seasoning (salt, pepper, vinegar, sugar) to balance.',
    'Serve the stroganoff over the cooked rice.',
  ],
  notes: 'If the sauce gets too thick, loosen with a splash of water. Use 2–3x oregano if using fresh.',
};
