export const tagine = {
  name: 'Chickpea Tagine',
  param: 'tagine',
  recipeImage: 'assets/images/tagine.png',
  star: false,
  introText:
    'A fragrant and hearty North African chickpea stew with preserved lemons, green olives, and aromatic spices.',
  description:
    'This traditional Moroccan chickpea tagine combines earthy chickpeas with the bright tang of preserved lemons, briny green olives, and sweet craisins. Aromatic spices and crunchy cashew nuts create a complex, satisfying dish that pairs perfectly with rice, bulgur, couscous, or quinoa.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Chickpeas',
      amount: 200,
      unit: 'g',
      flex: 'Lentils or any other beans can be used insteadß',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable stock',
      amount: 500,
      unit: 'ml',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: 'large',
      flex: 'Any onion variety works',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Preserved lemons',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Olives',
      amount: 0.5,
      unit: 'cup',
      flex: 'Any green olive variety works',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dates',
      amount: 0.25,
      unit: 'cup',
      flex: 'Dried apricots, craisins, or raisins can be used instead',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cashew nuts',
      amount: 0.25,
      unit: 'cup',
      flex: 'Almonds, walnuts, or cashews',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sumac',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Coriander',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ground ginger',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Fresh ginger can be grated and used instead',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Fresh cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Rice',
      amount: null,
      unit: '',
      flex: 'Any rice variety works. Also bulgur, couscous, or quinoa.',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Heat vegetable oil in a tagine or heavy-bottomed pot over medium heat.',
    'Slice onion and cook it until softened and translucent, about 5-7 minutes.',
    'Add minced or sliced garlic and cook for another minute until fragrant.',
    'Add ground spices (cumin, coriander, cinnamon, ginger) and cook for 30 seconds, stirring constantly to prevent burning.',
    'Add drained chickpeas and stir to coat with the spice mixture.',
    'Pour in vegetable stock and bring to a gentle boil.',
    'Add the preserved lemons, green olives, and dates to the pot.',
    'Season with salt, pepper, and sumac, then stir well to combine.',
    'Reduce heat to low, cover, and simmer for 25-30 minutes until the flavors have melded and the sauce has thickened slightly.',
    'In the last 5 minutes of cooking, add the cashew nuts.',
    'Taste and adjust seasoning as needed - add more salt, pepper, or sumac to taste.',
    'Serve hot over your choice of rice, bulgur, couscous, or quinoa.',
    'Garnish with fresh cilantro if desired.',
  ],
  notes:
    'This tagine tastes even better the next day as the flavors continue to develop. It can be made ahead and reheated gently. If you cannot find preserved lemons, you can make a quick substitute by mixing the zest and juice of 1 lemon with 1 tsp of salt. We can also use a pre-made spice-mix of your choosing instead of the individual spices listed. Instead of chickpeas, you can use lentils or any other beans you prefer. We can add some vegetables like carrots or zucchini for extra nutrition. We can even serve this with mashed potatoes instead of a grain. ',
};
