export const thaiBasilSauce = {
  name: 'Thai Basil Sauce',
  param: 'thai-basil-sauce',
  recipeImage: 'assets/images/thai-basil-sauce.jpg',
  star: false,
  introText: 'A quick and flavorful Thai basil sauce that brings a burst of flavor to any dish.',
  description:
    'This Thai basil sauce is a versatile and aromatic addition to your meals. It features fresh Thai basil, garlic, and a blend of savory sauces that create a rich and fragrant sauce. Perfect for drizzling over stir-fries, noodles, or as a dipping sauce.',
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Thai basil',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red bell pepper',
      amount: 0.5,
      unit: '',
      flex: 'Or another kind of bell pepper.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 6,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan oyster sauce',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark soy sauce',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any sugar, or something like mirin.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 0.5,
      unit: '',
      flex: 'Any onion will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 0.5,
      unit: 'tbsp',
      flex: 'Any chili flakes, hot sauce, or chili paste.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable stock',
      amount: 1,
      unit: 'cup',
      flex: 'Vietnamese stock is nice for this one.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Corn starch',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Add all ingredients to a pot and bring to a simmer on medium heat while stirring.',
    'When simmering, pour into ramekins or any other container like glasses and let cool for 30 min before storing in the fridge.',
    'Serve with any topping of your liking, like berries, coulis, nuts, or chocolate sauce.',
  ],
  notes: 'Serve with any bread. Rice, couscous, or quinoa are also great options.',
};
