export const yakiniku = {
  name: 'Yakiniku',
  param: 'yakiniku',
  recipeImage: 'assets/images/yakiniku.jpg',
  star: false,
  introText: 'Japanese-style BBQ with marinated soy mince, grilled vegetables, and aromatic sesame.',
  description:
    'Yakiniku brings the bold, savory flavors of Japanese BBQ to plant-based cooking. Soy mince is rehydrated and marinated in a mixture of soy sauce, mirin, sake, maple syrup, and gochujang, then grilled with colorful vegetables. Finished with toasted sesame seeds and scallions, it is perfect over rice or wrapped in lettuce leaves.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Soy mince',
      amount: 200,
      unit: 'g',
      flex: 'Textured vegetable protein (TVP)',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable broth',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Soy sauce',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mirin',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sake',
      amount: 1,
      unit: 'tbsp',
      flex: 'Water',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Maple syrup',
      amount: 1,
      unit: 'tbsp',
      flex: 'Sugar',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'thumb',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gochujang',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bell pepper',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrot',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallions',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Place soy mince in a bowl and cover with hot vegetable broth. Let sit for 10 minutes, then drain and squeeze out excess liquid.',
    'Mince the garlic and grate the ginger. Thinly slice the onion and bell pepper. Julienne the carrot. Slice the scallions.',
    'In a bowl, mix soy sauce, mirin, sake, maple syrup, sesame oil, garlic, ginger, and gochujang (if using) to make the yakiniku marinade.',
    'Add the rehydrated soy mince to the marinade. Mix well and let marinate for at least 10 minutes (longer for more flavor).',
    'Heat a grill pan or large skillet over medium-high heat. Add a little oil.',
    'Add the marinated soy mince, onion, bell pepper, and carrot. Stir-fry or grill until the soy mince is browned and the vegetables are tender, about 5-7 minutes.',
    'Sprinkle with toasted sesame seeds and scallions before serving.',
    'Serve with steamed rice, lettuce leaves, or as a filling for wraps.',
  ],
  notes:
    'You can add other vegetables like mushrooms, zucchini, or eggplant. For extra flavor, serve with additional yakiniku sauce or a squeeze of lemon.',
};
