export const aguaFrescaDeTamarindo = {
  name: 'Agua Fresca de Tamarindo',
  param: 'agua-fresca-tamarindo',
  recipeImage: 'assets/images/agua-fresca-de-tamarindo.jpg',
  star: false,
  introText: 'Refreshing Mexican tamarind water with a perfect balance of sweet and tangy flavors.',
  description:
    'This traditional Mexican agua fresca combines the distinctive sweet-tart flavor of tamarind with agave syrup for a naturally refreshing drink. Perfect for hot days, this drink captures the authentic taste of Mexico with just three simple ingredients.',
  category: 'beverage',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Water',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Agave syrup',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tamarind paste',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ice cubes',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Lime wedge',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'In a blender, combine the water, agave syrup, and tamarind paste.',
    'Blend on high speed for 30-60 seconds until the mixture is completely smooth and well combined.',
    'Taste and adjust sweetness by adding more agave syrup if desired.',
    'Strain the mixture through a fine-mesh sieve to remove any remaining tamarind fibers (optional for smoother texture).',
    'Pour into a glass filled with ice cubes.',
    'Garnish with a lime wedge if desired.',
    'Stir before drinking and serve immediately.',
  ],
  notes:
    'This agua fresca is best served fresh but can be stored in the refrigerator for up to 2 days. Stir well before serving as separation is natural. For a larger batch, simply multiply the ingredients proportionally. You can adjust the sweetness to taste by adding more or less agave syrup.',
};
