export const bulgurPilaf = {
  name: 'Bulgur Pilaf',
  param: 'bulgur-pilaf',
  recipeImage: 'assets/images/bulgur-pilaf.jpg',
  star: false,
  introText: 'Simple, fluffy bulgur simmered with onion, tomato, and broth for a cozy staple side.',
  description:
    'This straightforward bulgur pilaf delivers soft, fluffy grains cooked in savory vegetable broth with a light tomato note. It comes together fast and pairs with stews, grilled vegetables, or beans. Minimal ingredients, maximum comfort.',
  category: 'side',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Medium bulgur with vermicelli',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable broth',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 0.5,
      unit: 'pc',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato purée',
      amount: 2,
      unit: 'tbsp',
      flex: 'Tomato paste.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Finely dice the onion (and garlic if using).',
    'Heat vegetable oil in a saucepan over medium heat. Add onion and cook 10-20 minutes until caramelized. Add garlic; cook 30 seconds.',
    'Stir in tomato purée.',
    'Add bulgur; stir to coat in oil and aromatics for 30–60 seconds (light toasting improves flavor).',
    'Pour in vegetable broth, add chili flakes. Stir once, bring to a gentle simmer.',
    'Cover, reduce heat to low, and cook until liquid is absorbed and bulgur is tender, about 12-15 minutes for medium bulgur. Do not stir while cooking.',
    'Remove from heat and fluff gently with a fork.',
  ],
  notes:
    'Stir in herbs (parsley, dill) or a squeeze of lemon for a fresh finish. Fine bulgur needs less liquid (~1.5 cups) and 6–8 min cook; coarse needs a bit more (~2.25 cups) and 15–18 min. Leftovers keep 3–4 days refrigerated; reheat with a splash of water.',
};
