export const bulgurPilaf = {
  name: 'Bulgur Pilaf',
  param: 'bulgur-pilaf',
  recipeImage: 'assets/images/bulgur-pilaf.jpg',
  star: false,
  introText: 'Simple, fluffy bulgur simmered with onion, tomato, and broth for a cozy staple side.',
  description:
    'This straightforward bulgur pilaf delivers soft, fluffy grains cooked in savory vegetable broth with a light tomato note. It comes together fast and pairs with stews, grilled vegetables, or beans. Minimal ingredients, maximum comfort.',
  category: 'side',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Medium bulgur with vermicelli',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable broth',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 0.5,
      unit: 'pc',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato purée',
      amount: 2,
      unit: 'tbsp',
      flex: 'Tomato paste.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Finely dice the onion (and garlic if using).',
    'Heat olive oil in a saucepan over medium heat. Add onion and cook 3–4 minutes until softened and translucent. Add garlic; cook 30 seconds.',
    'Stir in tomato purée and cook 1 minute to lightly caramelize.',
    'Add bulgur; stir to coat in oil and aromatics for 30–60 seconds (light toasting improves flavor).',
    'Pour in vegetable broth, add salt and pepper. Stir once, bring to a gentle simmer.',
    'Cover, reduce heat to low, and cook until liquid is absorbed and bulgur is tender (about 12 minutes for medium bulgur). Do not stir while cooking.',
    'Remove from heat and rest covered 5 minutes. Fluff gently with a fork.',
    'Adjust seasoning (salt, pepper, a drizzle of oil) before serving.',
  ],
  notes:
    'For richer flavor add 1 tsp vegan butter at the end. Stir in herbs (parsley, dill) or a squeeze of lemon. Fine bulgur needs less liquid (~1.5 cups) and 6–8 min cook; coarse needs a bit more (~2.25 cups) and 15–18 min. Leftovers keep 3–4 days refrigerated; reheat with a splash of water.',
};
