export const burger = {
  name: 'Burger',
  param: 'burger',
  recipeImage: 'assets/images/burger.jpg',
  star: true,
  introText: 'Saucy and juicy burger with a perfect balance of flavors, topped with fresh ingredients.',
  description:
    'The composition of this burger has a patty made from plant mince, mayo, mustard, BBQ sauce, caramelized onions, and fresh lettuce. And it is served in a toasted bun.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Burger buns',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Plant-based mince',
      amount: 300,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Caramelized onion',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
      link: 'caramelized-onion',
    },
    {
      name: 'BBQ sauce',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
      link: 'bbq-sauce',
    },
    {
      name: 'Mayonnaise',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mustard',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lettuce',
      amount: 4,
      unit: 'leaves',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Tomato',
      amount: 1,
      unit: 'large',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Form the plant-based mince into 2 burger patties, slightly larger than your buns as they will shrink when cooking.',
    'Season both sides of the patties with salt and black pepper.',
    'Heat 1 tablespoon of vegetable oil in a large skillet or pan over medium-high heat.',
    'Cook the burger patties for 3-4 minutes on each side, or until nicely browned and cooked through.',
    'While the patties cook, slice the burger buns in half and toast them lightly in a toaster or dry pan.',
    'If using tomato, slice it into thin rounds.',
    'Spread mayonnaise on the bottom bun and mustard on the top bun.',
    'Place lettuce leaves on the bottom bun, followed by the cooked burger patty.',
    'Top with caramelized onions, tomato slices (if using), and BBQ sauce.',
    'Crown with the top bun and serve immediately.',
  ],
  notes:
    'These burgers pair perfectly with crispy fries or a fresh side salad. Store any leftover patties in the refrigerator for up to 3 days.',
};
