export const chickpeaCurry = {
  name: 'Chickpea Curry',
  param: 'chickpea-curry',
  recipeImage: '../assets/images/chickpea-curry.jpg',
  star: false,
  introText: 'A quick and easy chickpea curry that’s packed with flavor and perfect for a weeknight dinner.',
  description:
    'Chickpea Curry is a delicious and satisfying dish made with chickpeas simmered in a spiced tomato sauce. It’s a one-pot meal that’s easy to prepare and can be served with rice or bread. The combination of spices creates a warm and comforting flavor, making it a favorite for many.',
  category: 'main',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Tomatoes',
      amount: 400,
      unit: 'g',
      flex: 'Canned whole, fresh, crushed, puréed.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 25,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chickpeas',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 2,
      unit: '',
      flex: 'Any onion works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger, grated',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 2,
      unit: 'cube',
      flex: '1 tsp salt',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Any pepper works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Smoked paprika',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Turmeric',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gingerbread spice',
      amount: 2,
      unit: 'tsp',
      flex: '0.5 tsp cinnamon, 0.5 tsp nutmeg, 0.5 tsp allspice, 0.5 tsp cloves.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato paste',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ketchup',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bread',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Dice the potatoes, root celery, carrots, and parsnips into bite-sized pieces. Peel the vegetables if necessary.',
    'In a large pot, combine the diced vegetables, water, and bouillon. Bring to a boil over medium-high heat.',
    'Reduce the heat and simmer for 10 minutes.',
    'Stir in the lentils, ketchup, white pepper, dried oregano, chili (if using), and vinegar. Let it simmer for another 10 minutes to allow the flavors to meld.',
    'If you’d like a richer flavor, optionally serve with finely chopped garlic mixed with sour cream on top.',
    'Taste and adjust the seasoning as needed before serving.',
  ],
  notes:
    'This stew is versatile—you can swap out any root vegetables or add beans and faux meat for extra protein. For added depth, try roasting the vegetables before adding them to the pot. Adjust the spice level by increasing or decreasing the amount of chili or opting for a milder alternative.',
};
