export const chilaquiles = {
  name: 'Chilaquiles',
  param: 'chilaquiles',
  recipeImage: 'assets/images/chilaquiles.jpg',
  star: false,
  introText: 'A classic Mexican 🇲🇽 dish with crispy tortilla chips in flavorful salsa.',
  description:
    'A traditional Mexican 🇲🇽 comfort food that transforms stale tortilla chips into a delicious breakfast. The chips are simmered in a vibrant red or green salsa until they soften slightly while maintaining some texture. Topped with fresh ingredients like avocado, cheese, and onions, this dish is both satisfying and full of authentic Mexican flavors.',
  category: 'breakfast',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Tortilla',
      amount: 3,
      unit: '',
      flex: 'Tortilla chips.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salsa',
      amount: 1,
      unit: 'cup',
      flex: 'Chopped onion, tomato, chili, and salt.',
      optional: false,
      topping: false,
      done: false,
      link: 'salsa',
    },
    {
      name: 'Cream',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Melty cheese',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Onion',
      amount: 0.25,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Cut the tortillas into triangles or strips.',
    'Heat oil in a large skillet or pan over medium heat.',
    'Fry the tortilla pieces until golden and crispy, then set aside on a paper towel.',
    'Pour the salsa into the pan and bring to a gentle simmer.',
    'Add the fried tortilla pieces to the pan and gently stir to coat them with the salsa.',
    'Cook for 3-4 minutes, stirring occasionally, until the chips have softened slightly but still have some crunch.',
    'Pour the cream over the top and sprinkle with the melty cheese.',
    'Serve immediately, garnished with fresh cilantro and/or sliced onion if using.',
  ],
  notes:
    'Add fresh cilantro and/or onion on top as garnish. Chilaquiles are best served immediately after cooking to maintain the perfect texture balance between soft and crunchy chips. You can use store-bought salsa or make your own. This dish is traditionally eaten for breakfast or brunch and pairs well with refried beans, bolillo, and avocado slices.',
};
