export const chiliConCarne = {
  name: 'Chili Con Carne',
  param: 'chili-con-carne',
  recipeImage: 'assets/images/chili-con-carne.jpg',
  star: false,
  introText: 'A hearty, warming chili with soy mince and beans in tomato sauce.',
  description:
    'A rich and satisfying chili loaded with soy mince and beans simmered in a savory tomato base. Seasoned with garlic, hot sauce, and a touch of maple syrup for depth, this is comfort food at its best. Serve over rice for a complete meal.',
  category: 'dinner',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Beans in tomato sauce',
      amount: 400,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Puréed tomato',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Soy mince',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic cloves',
      amount: 5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ketchup',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Hot sauce',
      amount: 1,
      unit: 'tsp',
      flex: 'Any hot sauce, any chili flakes, any fresh or fried chili.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Maple syrup',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Slice the onion and garlic.',
    'Heat oil in a large pot over medium heat and sauté the onion and garlic until softened.',
    'Add the soy mince and cook, stirring, for a few minutes.',
    'Stir in the puréed tomato, beans in tomato sauce, and ketchup.',
    'Season with hot sauce, salt, white pepper, light soy sauce, and maple syrup to taste.',
    'Taste and adjust seasoning as needed.',
    'Serve over rice.',
  ],
  notes:
    'Adjust the hot sauce, soy sauce, and maple syrup to your liking — the balance of heat, salt, and sweetness is key. Leftovers taste even better the next day.',
};
