export const chiliOilNoodles = {
  name: 'Chili oil noodles',
  param: 'chili-oil-noodles',
  recipeImage: 'assets/images/chili-oil-noodles.jpg',
  star: false,
  introText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.',
  description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
  tags: {
    quick: true,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Noodles',
      amount: 150,
      unit: 'g',
      flex: 'Any noodles',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Oil',
      amount: 0.5,
      unit: 'cup',
      flex: 'Any vegetable oil',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 0.5,
      unit: 'cup',
      flex: 'Any chili flakes, fresh chili, crispy chili oil, or even hot sauce',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark soy',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Scallion',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cook the noodles.',
    'Add aromatics into a bowl.',
    'Heat up oil and when smoking hot, pour over the aromatics.',
    'Add sauces to the bowl.',
    'Add the noodles to the bowl and mix.',
    'Add any toppings.',
  ],
  notes: '',
};
