export const chocolateChipCookies = {
  name: 'Chocolate Chip Cookies',
  param: 'chocolate-chip-cookies',
  recipeImage: '../assets/images/chocolate-chip-cookies.jpg',
  star: false,
  introText:
    'Indulge in the timeless delight of warm, gooey chocolate chip cookies. Perfectly chewy with crispy edges, they’re the ultimate treat for any occasion.',
  description:
    'These vegan chocolate chip cookies are a delicious twist on the classic favorite. Made with plant-based ingredients, they’re perfect for anyone craving a nostalgic and comforting treat. Soft in the center and crispy on the edges, each bite is filled with melty chocolate goodness.',
  tags: {
    quick: true,
    easy: true,
    temperature: '350°F',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Butter',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Granulated sugar',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Plant-based milk',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vanilla extract',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'All-purpose flour',
      amount: 150,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan chocolate chips',
      amount: 90,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat your oven to 350°F (175°C) and line a baking sheet with parchment paper.',
    'In a mixing bowl, cream together the softened vegan butter, brown sugar, and granulated sugar until smooth and fluffy.',
    'Stir in the plant-based milk and vanilla extract until fully combined.',
    'In a separate bowl, whisk together the flour, baking soda, and salt.',
    'Gradually add the dry ingredients to the wet mixture, stirring until a soft dough forms. Be careful not to overmix.',
    'Fold in the vegan chocolate chips until evenly distributed.',
    'Scoop the dough onto the prepared baking sheet, spacing each cookie about 2 inches apart. Flatten slightly with your fingers or a spoon.',
    'Bake for 10-12 minutes, or until the edges are golden brown and the centers look slightly undercooked. They will firm up as they cool.',
    'Let the cookies cool on the baking sheet for 5 minutes before transferring to a wire rack to cool completely.',
  ],
  notes:
    'For extra indulgence, sprinkle a pinch of sea salt on top of the cookies before baking. You can also experiment with add-ins like chopped nuts, dried fruits, or different types of vegan chocolate for a unique twist!',
};
