export const cremeBrulee = {
  name: 'Crème Brûlée',
  param: 'creme-brulee',
  recipeImage: '../assets/images/creme-brulee.jpg',
  star: false,
  introText: 'Indulge in this silky vegan crème brûlée, a plant-based twist on the classic French dessert.',
  description:
    'This vegan crème brûlée offers a rich and creamy custard base topped with a caramelized sugar crust. Perfect for a dinner party or an indulgent treat, it’s surprisingly easy to make and uses simple, pantry-friendly ingredients.',
  tags: {
    quick: false,
    easy: true,
    temperature: '180',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Sugar',
      amount: 80,
      unit: 'g',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Corn starch',
      amount: 25,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan butter',
      amount: 40,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Plant-based milk',
      amount: 400,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vanilla extract',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 180°C (350°F).',
    'In a medium saucepan, whisk together the sugar, corn starch, and salt.',
    'Slowly add the plant-based milk while whisking continuously to avoid lumps.',
    'Place the saucepan over medium heat and cook the mixture, stirring constantly, until it thickens and resembles a custard consistency. This will take about 5–7 minutes.',
    'Remove the saucepan from the heat and stir in the vegan butter, lemon juice, and vanilla extract until fully incorporated.',
    'Pour the custard into ramekins and smooth the tops. Place the ramekins in a baking dish and fill the dish with hot water until it reaches halfway up the sides of the ramekins.',
    'Bake the custards in the preheated oven for 25–30 minutes or until they are set but still slightly jiggly in the center.',
    'Allow the ramekins to cool to room temperature, then refrigerate for at least 2 hours or until fully chilled.',
    'Before serving, sprinkle an even layer of sugar on top of each custard and use a kitchen torch to caramelize the sugar until it forms a golden, crispy crust. Alternatively, you can place the ramekins under a broiler for a few minutes to achieve the same effect.',
    'Serve immediately and enjoy the contrast of the creamy custard and the crackly caramel top.',
  ],
  notes:
    'For best results, use a kitchen torch to caramelize the sugar for a perfectly even crust. This dessert can be made a day in advance, but caramelize the sugar right before serving to maintain the crisp texture.',
};
