export const enfrijoladas = {
  name: 'Enfrijoladas',
  param: 'enfrijoladas',
  recipeImage: 'assets/images/enfrijoladas.jpg',
  star: false,
  introText: 'Soft tortillas bathed in a silky black bean sauce 🇲🇽.',
  description:
    'A humble Mexican 🇲🇽 dish where corn tortillas are dipped in a smooth, seasoned black bean sauce, then folded and topped with crumbly cheese, onion, and cream. Think of them as the bean-based cousin of enchiladas: quick, comforting, and built from pantry staples. The sauce gets its depth from sautéed onion, garlic, and a toasted chili blended right into the beans.',
  category: 'dinner',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Corn tortillas',
      amount: 8,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black beans',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Dried chili',
      amount: 1,
      unit: '',
      flex: 'Chipotle, ancho, or guajillo.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable broth',
      amount: 0.5,
      unit: 'cup',
      flex: 'Water or milk, to thin the sauce.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Crumbly cheese',
      amount: 100,
      unit: 'g',
      flex: 'Plant-based queso fresco or feta.',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Cream',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Onion',
      amount: 0.25,
      unit: '',
      flex: 'Thinly sliced.',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Heat a little oil in a pan over medium heat and sauté the chopped onion until soft and translucent.',
    'Add the garlic and the dried chili and cook for another minute until fragrant.',
    'Add the black beans with their liquid and the broth, then simmer for 5 minutes.',
    'Blend the bean mixture until completely smooth, adding more broth or water until it reaches a pourable, sauce-like consistency. Season with salt.',
    'Return the sauce to the pan and keep it warm over low heat.',
    'Warm the tortillas in a dry skillet or directly over a flame until soft and pliable.',
    'Dip each warm tortilla into the bean sauce to coat both sides, then fold in half or into quarters and arrange on a plate.',
    'Spoon extra sauce over the folded tortillas.',
    'Top with crumbled cheese, a drizzle of cream, sliced onion, and cilantro.',
  ],
  notes:
    'Serve immediately while warm, as the tortillas soften the longer they sit in the sauce. The sauce should be loose enough to coat a tortilla but not watery. Pair with refried beans, rice, or a fried egg on top for a heartier meal. Leftover sauce keeps well and can be thinned with a splash of water when reheating.',
};
