export const garlicPasta = {
  name: 'Garlic Pasta',
  param: 'garlic-pasta',
  recipeImage: 'assets/images/garlic-pasta.jpg',
  star: false,
  introText: 'Simple and elegant spaghetti with garlic and tomatoes sautéed in rich butter.',
  description:
    'This classic Italian-inspired pasta dish showcases the beautiful simplicity of quality ingredients. Fresh garlic and ripe tomatoes are gently sautéed in butter to create a light yet flavorful sauce that perfectly coats the spaghetti.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Spaghetti',
      amount: 80,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 1,
      unit: 'cube/tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Any pepper, chili, or chili flakes.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Fresh basil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Bring a pot of salted water to a boil for the pasta.',
    'While waiting for the water to boil, thinly slice the garlic cloves.',
    'Halve the cherry tomatoes or slice up regular tomatoes and set aside.',
    'Add the spaghetti to the boiling water and cook according to package directions until al dente, normally ~10 minutes.',
    'While the pasta cooks, heat the butter in a large skillet over medium heat.',
    'Add the sliced garlic to the melted butter.',
    'Immediately add the tomatoes to the skillet as well and cook for 3-4 minutes until they start to soften and release their juices.',
    'Add the vegetable bouillon and season black pepper to taste.',
    'Reserve 1 cup of pasta cooking water before draining the spaghetti.',
    'Drain the pasta and immediately add it to the skillet with the garlic and tomatoes.',
    'Toss everything together, adding a splash of pasta water if needed to help coat the noodles.',
    'Remove from heat and add fresh basil leaves if using.',
  ],
  notes:
    "Don't let the garlic brown too much or it will become bitter. The pasta water helps create a silky sauce that binds everything together.",
};
