export const gochujangPasta = {
  name: 'Gochujang Pasta',
  param: 'gochujang-pasta',
  recipeImage: 'assets/images/gochujang-pasta.jpg',
  star: false,
  introText: 'A fusion dish combining Korean gochujang with creamy Italian pasta for a spicy, umami-rich meal.',
  description:
    'This Gochujang Pasta brings together the best of Korean and Italian cuisines. The fermented heat of gochujang pepper paste is balanced with rich cream and savory soy sauce, creating a silky sauce that clings perfectly to pasta. Quick to prepare and packed with bold flavors, this dish is perfect for weeknight dinners when you want something exciting with minimal effort.',
  tags: {
    quick: true,
    easy: true,
    temperature: 'hot',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Pasta',
      amount: 75,
      unit: 'g',
      flex: 'Any pasta shape works - spaghetti, fettuccine, or penne are all good options.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gochujang',
      amount: 2,
      unit: 'tbsp',
      flex: 'Korean red pepper paste. Adjust amount based on spice preference.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 0.5,
      unit: 'cup',
      flex: 'Heavy cream or half-and-half. For a lighter version, try cashew cream.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 2,
      unit: 'tbsp',
      flex: 'Tamari or coconut aminos can be substituted for a gluten-free option.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: 'Minced or thinly sliced.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Spring onion',
      amount: 2,
      unit: '',
      flex: 'Sliced, with whites and greens separated.',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Butter',
      amount: 1,
      unit: 'tbsp',
      flex: 'Olive oil can be substituted.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tsp',
      flex: 'Balances the spice. Honey or maple syrup works too.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tsp',
      flex: 'Toasted for extra flavor.',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 0.5,
      unit: 'tsp',
      flex: 'For finishing the dish.',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Bring a pot of salted water to a boil and cook pasta according to package instructions until al dente. Reserve 1/4 cup of pasta water before draining.',
    'While the pasta cooks, separate the spring onions into white parts and green parts. Finely chop both, keeping them separate.',
    'Mince or thinly slice the garlic cloves.',
    'In a large skillet, melt the butter over medium heat. Add the white parts of the spring onions and garlic, cooking until fragrant, about 1-2 minutes.',
    'Reduce heat to medium-low and add the gochujang paste. Stir and cook for about 30 seconds to bloom the flavors.',
    'Pour in the cream and soy sauce, stirring well to incorporate the gochujang into a smooth sauce. Add sugar if using.',
    'Simmer gently for 2-3 minutes until the sauce begins to thicken slightly.',
    'Add the drained pasta to the sauce, along with a splash of the reserved pasta water. Toss well to coat the pasta evenly.',
    'If the sauce is too thick, add more pasta water a tablespoon at a time until you reach your desired consistency.',
    'Remove from heat and drizzle with sesame oil if using.',
    'Serve immediately, garnished with the green parts of the spring onions and a sprinkle of sesame seeds if desired.',
  ],
  notes:
    'For extra protein, add tofu or a plant-based meat alternative. You can also toss in vegetables like spinach, mushrooms, or bok choy. The sauce will thicken as it sits, so eat immediately for best results or thin with a splash of water when reheating. This dish has a good kick of heat - adjust the gochujang amount to your spice preference.',
};
