export const guacamole = {
  name: 'Guacamole',
  param: 'guacamole',
  recipeImage: 'assets/images/guacamole.jpg',
  star: true,
  introText: 'Fresh, creamy guacamole with a perfect balance of lime, cilantro, and serrano heat.',
  description:
    'This classic guacamole recipe delivers the perfect combination of creamy avocado, bright lime juice, fresh cilantro, and a kick of heat from serrano pepper. Simple ingredients come together to create the ultimate dip for chips, tacos, or any Mexican dish.',
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Avocados',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lime',
      amount: 1,
      unit: '',
      flex: 'Lemon.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Fresh cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Serrano pepper',
      amount: 1,
      unit: '',
      flex: 'Any chili pepper of your choice.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cut the avocados in half, remove the pits, and scoop the flesh into a mixing bowl.',
    'Mash the avocados with a fork to your desired consistency - chunky or smooth.',
    'Cut the lime in half and squeeze the juice directly into the bowl with the mashed avocado.',
    'Finely chop the cilantro and add it to the bowl.',
    'Finely mince the serrano pepper, removing seeds if you prefer less heat, and add to the mixture.',
    'Add the salt and mix everything together gently.',
    'If using tomato, dice it finely (removing seeds to prevent excess moisture) and fold it in last.',
    'Taste and adjust seasoning with more lime juice, salt, or serrano as needed.',
  ],
  notes:
    'The key to great guacamole is using perfectly ripe avocados and fresh lime juice. Press plastic wrap directly onto the surface of leftover guacamole to minimize browning. This guacamole pairs perfectly with tortilla chips, tacos, burritos, or as a topping for grilled meats. Best enjoyed fresh, but can be stored in the refrigerator for up to 2 days.',
};
