export const hokkienMee = {
  name: 'Hokkien Mee',
  param: 'hokkien-mee',
  recipeImage: 'assets/images/hokkien-mee.jpg',
  star: false,
  introText: 'A rich, savory stir-fried noodle dish with a dark, glossy sauce, loaded with vegetables and tofu.',
  description:
    'Hokkien Mee is a beloved Southeast Asian noodle dish known for its deeply savory, slightly sweet dark sauce. This version features a hearty stir fry of napa cabbage, mushrooms, and tofu, all tossed with thick noodles and a punchy sauce of light and dark soy, oyster sauce, corn syrup, and chili oil.',
  category: ['main'],
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Light soy sauce',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark soy sauce',
      amount: 4,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan oyster sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Corn syrup',
      amount: 2,
      unit: 'tbsp',
      flex: 'Any syrup',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili oil',
      amount: 2,
      unit: 'tbsp',
      flex: 'Sambal or sriracha',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Napa cabbage',
      amount: 1,
      unit: '',
      flex: 'Bok choy or regular cabbage',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mushrooms',
      amount: 1,
      unit: 'cup',
      flex: 'Shiitake, oyster, or any variety',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tofu',
      amount: 200,
      unit: 'g',
      flex: 'Smoked tofu',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Noodles',
      amount: 3,
      unit: 'servings',
      flex: 'Thick yellow noodles, udon, or egg noodles',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Mix the sauce: combine light soy sauce, dark soy sauce, oyster sauce, corn syrup, and chili oil in a bowl. Set aside.',
    'Cook the noodles according to package instructions, drain, and set aside.',
    'Slice the onion, mince the garlic, chop the napa cabbage, slice the mushrooms, and cube the tofu.',
    'Heat oil in a wok or large pan over high heat. Sear the tofu until golden on all sides, then remove and set aside.',
    'In the same wok, stir fry the onion and garlic until fragrant, about 1 minute.',
    'Add the mushrooms and cook until they start to brown, about 2-3 minutes.',
    'Add the napa cabbage and stir fry until slightly wilted, about 1-2 minutes.',
    'Return the tofu to the wok, add the noodles, and pour the sauce over everything.',
    'Toss everything together over high heat until the noodles are well coated and the sauce is absorbed, about 2 minutes.',
    'Serve immediately.',
  ],
};
