export const iceCream = {
  name: 'Ice Cream',
  param: 'ice-cream',
  recipeImage: 'assets/images/ice-cream.jpg',
  star: false,
  introText: 'My ice cream brings all the people to the yard.',
  description:
    'Ice cream is a frozen dessert made from a mixture of milk, cream, sugar, and flavorings. With an ice cream machine, you can easily make your own homemade ice cream and customize it to your liking. So grab a scoop and enjoy the creamy goodness of homemade ice cream.',
  category: 'dessert',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Milk',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 1,
      unit: 'cup',
      flex: 'Can be replaced with more milk, or half the amount with milk.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ice cream stabilizer',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flavored syrup',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Popping candy',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Mix the sugar and ice cream stabilizer in a bowl. Add the salt and mix well.',
    'In a saucepan, heat the milk and cream together with the sugar-stabilizer-salt mixture on medium heat, stirring constantly, until the mixture reaches 65°C (150°F).',
    'Remove from heat. If using, add the syrup and mix well.',
    'Pour the mixture into your ice cream machine and churn.',
    'If using, add the popping candy just before the ice cream is done (after ~50 minutes).',
  ],
  notes: 'For a fun variation, try adding fruit or other flavorings.',
};
