export const lemonTahiniDressing = {
  name: 'Lemon Tahini Dressing',
  param: 'lemon-tahini-dressing',
  recipeImage: 'assets/images/lemon-tahini-dressing.jpg',
  star: false,
  introText: 'A creamy, tangy tahini dressing that pairs beautifully with any salad or roasted vegetables.',
  description:
    'This classic lemon tahini dressing is rich, creamy, and perfectly balanced. The combination of tahini, fresh lemon juice, and Dijon mustard creates a versatile dressing that works on everything from leafy greens to roasted vegetables. A touch of garlic and agave adds depth and subtle sweetness.',
  category: 'condiment',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Tahini',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Olive oil',
      amount: 0.125,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon',
      amount: 0.25,
      unit: 'cup',
      flex: 'Yuzu, lime, or any other citrus will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Agave syrup',
      amount: 0.125,
      unit: 'cup',
      flex: 'Any sweetener will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dijon mustard',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Add all ingredients to a blender or food processor.',
    'Blend until smooth and creamy, about 1-2 minutes.',
    'If the dressing is too thick, add water 1 tablespoon at a time until desired consistency is reached.',
    'Taste and adjust seasoning with more salt, lemon juice, or agave as needed.',
  ],
  notes: 'Try a 50/50 mix of lemon & yuzu. This dressing thickens when chilled, so thin with water if needed. Store in refrigerator for up to 1 week. Stir before using as ingredients may separate.',
};
