export const lynchburgLemonade = {
  name: 'Lynchburg Lemonade',
  param: 'lynchburg-lemonade',
  recipeImage: 'assets/images/lynchburg-lemonade.jpg',
  star: false,
  introText: 'A refreshing Tennessee whiskey cocktail with bright lemon and lemon-lime soda.',
  description:
    'Named after the home of Jack Daniel’s in Lynchburg, Tennessee, this classic cocktail blends Tennessee whiskey and triple sec with fresh lemon juice and a splash of lemon-lime soda. The result is a fizzy, citrusy, and surprisingly easy-drinking long drink that tastes just like a boozy lemonade.',
  category: 'beverage',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Tennessee whiskey',
      amount: 1,
      unit: 'oz',
      flex: 'Jack Daniel’s is traditional, but any Tennessee or bourbon whiskey works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Triple sec',
      amount: 1,
      unit: 'oz',
      flex: 'Cointreau or any orange liqueur.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Fresh lemon juice',
      amount: 1,
      unit: 'oz',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Simple syrup',
      amount: 0.5,
      unit: 'oz',
      flex: 'Adjust to taste, or omit if your soda is sweet enough.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon-lime soda',
      amount: 4,
      unit: 'oz',
      flex: 'Sprite or 7UP.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ice cubes',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon slice',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Maraschino cherry',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Fill a tall glass with ice cubes.',
    'Add the Tennessee whiskey, triple sec, fresh lemon juice, and simple syrup if using.',
    'Top with the lemon-lime soda.',
    'Stir gently to combine without losing too much fizz.',
    'Taste and adjust sweetness with more simple syrup if needed.',
    'Garnish with a lemon slice and a maraschino cherry.',
    'Serve immediately while cold and bubbly.',
  ],
  notes:
    'For a pitcher, multiply the spirits, lemon juice, and syrup proportionally and add the soda just before serving so it stays fizzy. Always use freshly squeezed lemon juice for the brightest flavor. For a non-alcoholic version, replace the whiskey and triple sec with extra lemonade and a splash of orange juice.',
};
