export const makhani = {
  name: 'Makhani',
  param: 'makhani',
  recipeImage: 'assets/images/makhani.jpg',
  star: false,
  introText: 'A simple template for a flavorful Makhani curry, customizable with your choice of protein and spices.',
  description:
    'Makhani is a rich and creamy Indian curry, traditionally made with butter and cream. This version is easy to make and can be customized with your choice of protein, such as chickpeas or tofu. The spices create a warm and comforting flavor, making it a favorite for many. Serve it with rice or naan for a complete meal.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: 'Any onion works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 25,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato paste',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomatoes',
      amount: 300,
      unit: 'g',
      flex: 'Canned whole, fresh, crushed, puréed.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Coriander',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Turmeric',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili powder',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any sweetener works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garam masala',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Creme fraiche',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 0.5,
      unit: 'cup',
      flex: 'Coconut cream',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Fresh cilantro',
      amount: 2,
      unit: 'tbsp',
      flex: 'For garnish.',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Finely dice the red onion and mince or grate the garlic and ginger.',
    'Heat butter in a large pan over medium heat. Add the onions and cook until soft and translucent, about 5 minutes.',
    'Add the minced garlic and ginger, cooking for another 1-2 minutes until fragrant.',
    'Add the tomato paste along with all the spices except the garam masala (cumin, coriander, turmeric, chili powder, salt, and MSG if using) and toast for 30 seconds until fragrant.',
    'Pour in the crushed tomatoes, garam masala, and sugar. Simmer for 10 minutes, stirring occasionally.',
    'Turn off the heat and stir in the creme fraiche and cream until fully incorporated and warmed through. Adjust seasoning to taste',
    'Finish with lemon juice and adjust seasoning to taste.',
    'Garnish with fresh cilantro if desired and serve hot with rice, roti, paratha, or naan.',
  ],
  notes:
    'This recipe is a template. Feel free to add your choice of protein, such as chickpeas, lentils, or tofu. Adjust the spices to your preference for heat and flavor. Serve with rice, roti, paratha, or naan for a complete meal.',
};
