export const mangoChutneycurry = {
  name: 'Mango Chutney Curry',
  param: 'mango-chutney-curry',
  recipeImage: 'assets/images/mango-chutney-curry.jpg',
  star: false,
  introText: 'A sweet and savory curry featuring mango chutney as the star ingredient, served with fluffy rice.',
  description:
    'This aromatic curry combines the sweetness of mango chutney with warming spices to create a perfectly balanced dish. Chickpeas provide protein while vegetables add texture and nutrition. The mango chutney gives this curry its distinctive sweet-tangy flavor profile that pairs beautifully with rice.',
  category: 'main',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: 1.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Coriander',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Turmeric',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garam masala',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mango chutney',
      amount: 0.5,
      unit: 'cup',
      flex: 'Store-bought or homemade.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chickpeas',
      amount: 400,
      unit: 'g',
      flex: 'Canned, drained.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Coconut milk',
      amount: 400,
      unit: 'ml',
      flex: 'Full-fat.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Diced tomatoes',
      amount: 400,
      unit: 'g',
      flex: 'Canned or fresh.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red bell pepper',
      amount: 1,
      unit: '',
      flex: 'Any color bell pepper works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baby spinach',
      amount: 2,
      unit: 'cups',
      flex: 'Fresh.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable stock',
      amount: 1,
      unit: 'cup',
      flex: 'Or water with bouillon cube.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: 'To taste.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Freshly ground.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Fresh cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: 'For garnish.',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Lime wedges',
      amount: 1,
      unit: '',
      flex: 'For serving.',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Cook the basmati rice according to package instructions and set aside.',
    'Heat coconut oil in a large pot over medium heat.',
    'Add diced onion and cook for 5-7 minutes until softened and translucent.',
    'Add minced garlic and grated ginger, cooking for another 1-2 minutes until fragrant.',
    'Add cumin, coriander, turmeric, and garam masala. Cook for 30 seconds, stirring constantly to prevent burning.',
    'Stir in the mango chutney and cook for 2 minutes to caramelize slightly.',
    'Add diced tomatoes, coconut milk, and vegetable stock. Bring to a gentle simmer.',
    'Add chickpeas and diced bell pepper. Simmer for 15-20 minutes until the sauce thickens and vegetables are tender.',
    'Stir in the baby spinach and cook until wilted, about 2-3 minutes.',
    'Season with salt and black pepper to taste.',
    'Serve hot over the cooked rice, garnished with fresh cilantro and lime wedges.',
  ],
  notes:
    'This curry tastes even better the next day as the flavors develop. Adjust the sweetness by adding more or less mango chutney to your taste. For extra heat, add a pinch of chili flakes or a chopped chili pepper.',
};
