export const mapoTofu = {
  name: 'Mapo Tofu',
  param: 'mapo-tofu',
  recipeImage: '../assets/images/mapo-tofu.jpg',
  star: true,
  introText: 'A classic Sichuan dish featuring silky tofu in a spicy, savory sauce.',
  description:
    'Mapo Tofu is a beloved Sichuan recipe characterized by its bold flavors from doubanjiang, garlic, ginger, and Sichuan peppercorns. This dish combines soft tofu with ground pork (or a vegetarian substitute) and is finished with a touch of cornstarch slurry for a silky sauce. Perfect served over steamed rice.',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Soft tofu',
      amount: 400,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ground pork',
      amount: 200,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Doubanjiang (chili bean paste)',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'inch',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallion',
      amount: 2,
      unit: '',
      flex: 'chopped (reserve some for garnish)',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sichuan peppercorns',
      amount: 0.5,
      unit: 'tsp',
      flex: 'ground',
      optional: false,
      topping: false,
      done: false,
    },
    { name: 'Chicken broth', amount: 1, unit: 'cup', flex: '', optional: false, topping: false, done: false },
    { name: 'Soy sauce', amount: 1, unit: 'tbsp', flex: '', optional: false, topping: false, done: false },
    {
      name: 'Cornstarch slurry',
      amount: 1,
      unit: 'tbsp',
      flex: 'mixed with equal water',
      optional: false,
      topping: false,
      done: false,
    },
    { name: 'Chili oil', amount: 1, unit: 'tbsp', flex: '', optional: false, topping: false, done: false },
    { name: 'Oil', amount: 1, unit: 'tbsp', flex: '', optional: false, topping: false, done: false },
  ],
  instructions: [
    'Heat oil in a pan over medium-high heat. Add minced garlic, ginger, and half of the scallions. Sauté until fragrant.',
    'Add the ground pork and cook until browned.',
    'Stir in the doubanjiang and soy sauce; cook for another minute.',
    'Pour in the chicken broth and bring to a simmer.',
    'Gently add the tofu cubes and simmer for 5–7 minutes, allowing the flavors to meld.',
    'Stir in the chili oil and sprinkle in the ground Sichuan peppercorns.',
    'Add the cornstarch slurry to thicken the sauce, stirring carefully to avoid breaking the tofu.',
    'Garnish with the reserved scallions and serve hot over steamed rice.',
  ],
  notes: 'For a vegetarian version, substitute ground pork with finely chopped mushrooms or plant-based mince.',
};
