export const mirzaGhasemi = {
  name: 'Mirza Ghasemi',
  param: 'mirza-ghasemi',
  recipeImage: 'assets/images/mirza-ghasemi.jpg',
  star: false,
  introText: 'A delicious Persian eggplant dish that is perfect for breakfast, lunch, or dinner.',
  description:
    "Mirza Ghasemi is a traditional Persian dish made with eggplant, tomatoes, garlic, and eggs. It's a simple and flavorful dish that is perfect for breakfast, lunch, or dinner. The smoky flavor of the eggplant combined with the sweetness of the tomatoes and the richness of the eggs makes this dish a real treat. Serve it with some warm bread or rice for a satisfying meal that will leave you feeling full and happy.",
  tags: {
    quick: true,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Eggplant',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato',
      amount: 1,
      unit: 'cup',
      flex: 'Either crushed tomatoes, puréed tomatoes, whole canned tomatoes, or oven-roasted fresh tomatoes.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 1,
      unit: '',
      flex: 'Fresh garlic.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: 'Black salt is preferable.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Pepper',
      amount: 1,
      unit: 'tsp',
      flex: "It don't matter if you're black or white🕺🏽.",
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato paste',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Turmeric',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Add all ingredients to a pot and bring to a simmer on medium heat while stirring.',
    'When simmering, pour into ramekins or any other container like glasses and let cool for 30 min before storing in the fridge.',
    'Serve with any topping of your liking, like berries, coulis, nuts, or chocolate sauce.',
  ],
  notes: 'Serve with any bread. Rice, couscous, or quinoa are also great options.',
};
