export const muffins = {
  name: 'Muffins',
  param: 'muffins',
  recipeImage: '../assets/images/muffins.jpg',
  star: false,
  introText:
    'These moist and hearty classic muffins are a delicious twist on a classic sponge cake. Perfect for a wholesome breakfast or snack!',
  description:
    'Classic muffins are soft, fluffy, and lightly sweetened individual cakes, perfect for breakfast or a snack. They have a tender crumb and a golden top, and can be enjoyed plain or with a variety of mix-ins like fruit, chocolate chips, or nuts. Easy to make and endlessly versatile, muffins are a staple in home baking.',
  category: 'dessert',
  tags: {
    quick: true,
    easy: true,
    temperature: '225',
    clean: true,
    cheap: true,
  },
  versions: [
    {
      name: 'Oat Muffins',
      param: 'oat-muffins',
    },
    {
      name: 'Banana Muffins',
      param: 'banana-muffins',
    },
    {
      name: 'Banana Oat Muffins',
      param: 'banana-oat-muffins',
    },
    {
      name: 'Mango Serrano Muffins',
      param: 'mango-serrano-muffins',
    },
    {
      name: 'Basil Strawberry Muffins',
      param: 'basil-strawberry-muffins',
    },
    {
      name: 'Chocolate Muffins',
      param: 'chocolate-muffins',
    },
    {
      name: 'Blueberry Yuzu Muffins',
      param: 'blueberry-yuzu-muffins',
    },
  ],
  ingredients: [
    {
      name: 'Flour',
      amount: 160,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 140,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vanilla extract',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any light-colored vinegar or citrus juice.',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 225°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and the sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the oil, milk, as well as vanilla extract and vinegar if using.',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'Bake for 18 minutes if using small muffin ramekins, 22 min if using large muffin ramekins, or until a toothpick inserted into the center comes out clean. Decrease the temperature to 175°C after 5-7 minutes.',
    'Allow the muffins to cool in the tin for 20 minutes before serving.',
  ],
  notes:
    'Store in an airtight container or bag at room temperature for up to 3 days, or refrigerate for longer freshness. Can also be frozen. Sprinkle sugar on top for a sweet, crusty surface. If mixing in berries like blueberries or strawberries, add up to 100g and increase the time baking with 4 extra minutes.',
};
