export const mushroomPasta = {
  name: 'Mushroom Pasta',
  param: 'mushroom-pasta',
  recipeImage: '../assets/images/mushroom-pasta.jpg',
  star: false,
  introText: 'A creamy and flavorful mushroom pasta that is quick and easy to make, perfect for a weeknight dinner.',
  description:
    'This mushroom pasta combines the earthy flavors of mushrooms with a creamy sauce, creating a comforting and satisfying dish. The addition of bouillon enhances the umami taste, while the optional chickpeas or other protein add a boost of nutrition.',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Spaghetti',
      amount: 150,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 3,
      unit: 'cups',
      flex: '3/4 pint',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bouillon cube',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mushrooms',
      amount: null,
      unit: '',
      flex: 'Season with salt, white pepper, MSG, dijon mustard, and sugar',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: null,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chickpeas or other protein',
      amount: null,
      unit: '',
      flex: 'Optional',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Season the mushrooms with salt, white pepper, MSG, dijon mustard, and sugar.',
    'Cook the mushrooms with seasoning in butter over medium heat.',
    'Add water and bouillon cube, then add the spaghetti.',
    'Cook under a lid for about 10 minutes on medium heat (6), checking and stirring once after 5 minutes.',
    'Add cream and optional chickpeas or other protein, and cook until the pasta is done and the sauce is creamy.',
  ],
  notes: 'This mushroom pasta is best served immediately. Adjust the seasoning to taste and enjoy a comforting meal.',
};
