export const okonomiyaki = {
  name: 'Okonomiyaki',
  param: 'okonomiyaki',
  recipeImage: '../assets/images/okonomiyaki.jpg',
  star: false,
  introText:
    'A savory Japanese pancake loaded with vegetables and topped with a tangy-sweet sauce, creamy mayo, and a variety of umami-rich garnishes.',
  description:
    'Okonomiyaki is a classic Japanese comfort food that translates to "grill what you like." This vegan version features a light and fluffy batter, a medley of fresh vegetables, and a delightful combination of toppings that make each bite an explosion of flavors. Whether you’re hosting friends or enjoying a cozy night in, this dish is sure to impress!',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cornstarch',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water or dashi',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Green cabbage, finely shredded',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrots, shredded',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallions, chopped',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Shiitake mushrooms, thinly sliced',
      amount: 1,
      unit: 'handful',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Pickled ginger (beni shoga), finely chopped',
      amount: 1,
      unit: 'small handful',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Okonomiyaki sauce',
      amount: '',
      unit: '',
      flex: 'homemade or store-bought',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Vegan Japanese-style mayo',
      amount: '',
      unit: '',
      flex: 'homemade or store-bought',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Aonori or crushed nori sheets',
      amount: '',
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Toasted sesame seeds',
      amount: '',
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Extra scallions, sliced',
      amount: '',
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Pickled ginger (beni shoga)',
      amount: '',
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'In a large bowl, whisk together the flour, cornstarch, baking powder, sugar, water (or dashi), and soy sauce until you have a smooth batter.',
    'Add the shredded cabbage, carrots, scallions, and any optional add-ins like mushrooms or pickled ginger to the batter. Mix until the vegetables are evenly coated.',
    'Heat a large non-stick skillet or griddle over medium heat and lightly grease with a small amount of oil.',
    'Spoon a portion of the batter onto the skillet and shape it into a round pancake, about 1/2 inch thick. Cook for 4-5 minutes on one side until golden brown and set, then carefully flip and cook for another 3-4 minutes on the other side.',
    'Transfer the cooked okonomiyaki to a plate and repeat with the remaining batter.',
    'Drizzle the okonomiyaki with okonomiyaki sauce and vegan Japanese-style mayo. Sprinkle with aonori or crushed nori, toasted sesame seeds, extra scallions, and pickled ginger.',
    'Serve immediately and enjoy!',
  ],
  notes:
    'Feel free to customize your okonomiyaki with your favorite vegetables and toppings. If you don’t have access to okonomiyaki sauce or vegan Japanese mayo, homemade versions are quick and easy to whip up. For an extra crispy texture, try cooking the okonomiyaki on a well-heated griddle. This dish is perfect for sharing or enjoying as a main course!',
};
