export const overnightOats = {
  name: 'Overnight Oats',
  param: 'overnight-oats',
  recipeImage: '../assets/images/overnight-oats.jpg',
  star: false,
  introText:
    'These easy and nutritious overnight oats are perfect for busy mornings. Packed with fiber, protein, and healthy fats, they make a balanced and delicious breakfast that you can prepare ahead of time.',
  description:
    'Overnight oats are a simple make-ahead breakfast option that’s both healthy and customizable. Rolled oats are soaked in plant-based milk, combined with chia seeds, flax seeds, a hint of cinnamon, and a touch of sweetness from syrup. Top them with your favorite nuts, seeds, or dried fruits for extra texture and flavor.',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Oats',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Syrup',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chia seeds',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Nutritional yeast',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Flax seeds',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Pumpkin seeds',
      amount: '',
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Sunflower seeds',
      amount: '',
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Walnuts',
      amount: '',
      unit: '',
      flex: 'Any nuts',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Dried cranberries',
      amount: '',
      unit: '',
      flex: 'Raisins or other dried fruits.',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'In a bowl or jar, combine the oats, milk, syrup, chia seeds, sesame seeds, nutritional yeast, flax seeds, cinnamon, and salt.',
    'Mix everything together until well combined.',
    'Cover and store in the refrigerator for at least one hour, or preferably overnight, to allow the oats to soak and thicken.',
    'When ready to eat, top with your favorite toppings like pumpkin seeds, walnuts, sunflower seeds, or dried cranberries.',
    'Serve chilled and enjoy a nutrient-packed start to your day.',
  ],
  notes:
    'Feel free to adjust the sweetness or add more spices like nutmeg or cardamom for extra flavor. You can also experiment with different plant-based milks or add a spoonful of peanut butter or fruit preserves for added richness.',
};
