export const pancakes = {
  name: 'Pancakes',
  param: 'pancakes',
  recipeImage: 'assets/images/pancakes.jpg',
  star: true,
  introText: 'Swedish-style.',
  description:
    "These pancakes are a classic Swedish dish that's perfect for breakfast or brunch. They're light, fluffy, and delicious, and they're easy to make with just a few simple ingredients. Serve them with your favorite toppings, like fresh berries, whipped cream, or maple syrup.",
  tags: {
    quick: true,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Flour',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: null,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Half the amount of baking soda.',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Mix flour, baking powder, sugar, and salt in a bowl.',
    'Pour in the milk while stirring to avoid lumps forming.',
    'Add butter to a pan on medium high heat and fry the pancake. Flip when bottom is turning golden in color.',
  ],
  notes: '',
};
