export const picoDeGallo = {
  name: 'Pico de Gallo',
  param: 'pico-de-gallo',
  recipeImage: 'assets/images/pico-de-gallo.jpg',
  star: false,
  introText: 'Fresh, crunchy tomato salsa with lime, cilantro, onion, jalapeño, and a clean salty kick.',
  description:
    'Pico de gallo (salsa fresca) is a bright, chunky mix of diced tomato, onion, jalapeño, cilantro, lime, and salt. It adds fresh acidity and texture anywhere you use salsa—tacos, bowls, or as a simple dip. The minimal ingredient list highlights clean flavors; quality salt and a squeeze of lime pull everything together.',
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Yellow onion',
      amount: 0.25,
      unit: '',
      flex: 'Any onion.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Jalapeño',
      amount: 1,
      unit: 'tbsp',
      flex: 'Serrano.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lime',
      amount: 0.5,
      unit: '',
      flex: 'Lemon.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Finely dice the onion and jalapeño. Mince the cilantro. Dice the tomato into small even cubes.',
    'Add tomato, onion, jalapeño, cilantro, salt, and juice from the 1/2 lime to a bowl.',
    'Toss until evenly combined. Let sit 5–10 minutes so salt draws out tomato juices and flavors meld.',
    'Taste and adjust salt or lime. If too sharp, add a pinch more salt. If flat, add a squeeze more lime.',
  ],
  notes:
    'Optional flavor boosts: 1 tbsp finely diced preserved lemon, a pinch of Japanese umami salt, or a pinch of MSG for depth. Drain excess liquid if using in tacos to prevent sogginess. You can scale easily; keep roughly equal parts tomato and onion with jalapeño to taste.',
};
