export const poke = {
  name: 'Poké',
  param: 'poke',
  recipeImage: 'assets/images/poke.jpg',
  star: true,
  introText: 'A customizable and refreshing vegan poké bowl, perfect for a quick and healthy meal.',
  description:
    "This vegan poké bowl features a base of seasoned rice topped with marinated tofu, fresh vegetables, and a savory soy-based dressing. It's easy to adapt with your favorite toppings.",
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: 200,
      unit: 'g',
      flex: 'Any rice works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Rice vinegar',
      amount: 1,
      unit: 'tsp',
      flex: 'Any vinegar works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Agave syrup',
      amount: 1,
      unit: 'tsp',
      flex: 'Any sweetener works e.g. sugar, maple syrup etc.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Firm tofu',
      amount: 100,
      unit: 'g',
      flex: 'Any bean like edamame beans or chickpeas, or lentils.',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Sesame oil',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 1,
      unit: 'clove',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Avocado',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Cucumber',
      amount: 0.25,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Edamame',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Mango',
      amount: 0.5,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Spring onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Nori (seaweed sheets)',
      amount: 0.5,
      unit: 'sheet',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Sesame Seeds',
      amount: 1,
      unit: 'tsp',
      flex: 'Toasted or untoasted.',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Cashew nuts',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Roasted onion',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Kimchi',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Toubanjao',
      amount: 1,
      unit: 'tsp',
      flex: 'Sriracha or other chili sauce, or chili flakes.',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Cook the rice your preferred way.',
    'Cut the tofu into 1/2-inch cubes. Fry or bake until golden brown and crispy if preferred.',
    'In a bowl, whisk together the light soy sauce, sesame oil, agave syrup, toubanjao, rice vinegar, minced garlic, and grated ginger.',
    'Prepare the toppings: Slice the avocado, cucumber, and mango. Thinly slice the spring onions, and cut the nori sheet into strips.',
    'Assemble the bowls: Divide the seasoned rice among bowls. Top with the marinated tofu, avocado, cucumber, edamame, carrot, and spring onions.',
    'Garnish with nori strips, sesame seeds, and chili flakes (if desired).',
    'Drizzle with extra marinade or your favorite poké dressing if needed.',
  ],
  notes:
    'Feel free to add other toppings like pickled ginger, radishes, mango, or corn. For extra flavor, toast the sesame seeds before sprinkling. The marinade for the tofu can also serve as a light dressing.',
};
