export const ponche = {
  name: 'Ponche',
  param: 'ponche',
  recipeImage: 'assets/images/ponche.jpg',
  star: false,
  introText: 'A warm, fruity Mexican punch simmered with hibiscus, tamarind, guava, and cinnamon.',
  description:
    'Ponche is a traditional Mexican holiday punch made by simmering a medley of fruits, dried flowers, and spices in water with brown sugar. Hibiscus and tamarind add tartness, guava and raisins bring sweetness, and sugarcane and cinnamon tie it all together. Served hot, it fills the kitchen with a fragrant, festive aroma.',
  category: 'drink',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Hibiscus flowers',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tamarind',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Guava',
      amount: 2,
      unit: '',
      flex: 'Apple or pear',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Raisins',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugarcane',
      amount: 1,
      unit: 'stalk',
      flex: 'Piloncillo or extra brown sugar',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Hawthorne',
      amount: 0.5,
      unit: 'cup',
      flex: 'Dried cranberries or dried apricots',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon stick',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cut the guava into quarters and the sugarcane into small sticks. Remove seeds from the tamarind if needed.',
    'In a large pot, bring about 8 cups of water to a boil.',
    'Add the cinnamon stick, hibiscus flowers, tamarind, and hawthorne. Simmer for 10 minutes.',
    'Add the guava, sugarcane, and raisins. Continue simmering for 15-20 minutes until the fruits are soft.',
    'Stir in the brown sugar until dissolved. Taste and adjust sweetness as needed.',
    'Serve hot in mugs, scooping some fruit into each serving.',
  ],
  notes:
    'Traditionally served during Las Posadas and Christmas celebrations. You can add other fruits like tejocotes, prunes, or sliced oranges. Adjust sweetness to taste. Keeps well refrigerated and can be reheated.',
};
