import { tapenade } from './tapenade';
import { pesto } from './pesto';
import { chiliOilNoodles } from './chili-oil-noodles';
import { stickyBananaSpongePudding } from './sticky-banana-sponge-pudding';

export const Recipes = [
  //   Template
  // {
  //   name: 'Recipe',
  //   param: 'recipe',
  //   recipeImage: '../assets/images/recipe.jpg',
  //   star: false,
  //   introText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.',
  //   description:
  //     'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
  //   tags: {
  //     quick: false,
  //     easy: false,
  //     temperature: null,
  //     clean: false,
  //     cheap: false,
  //   },
  //   ingredients: [
  //     {
  //       name: 'MSG',
  //       amount: 1,
  //       unit: 'tbsp',
  //       flex: '',
  //       optional: false,
  //       topping: false,
  //       done: false,
  //     },
  //   ],
  //   instructions: [
  //     'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  //     'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  //     'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  //     'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  //     'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  //   ],
  //   notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  // },
  tapenade,
  chiliOilNoodles,
  pesto,
  stickyBananaSpongePudding,
  //  Coffee Tres Leches
  {
    name: 'Coffee Tres Leches',
    param: 'coffee-tres-leches',
    recipeImage: '../assets/images/coffee-tres-leches.jpg',
    star: false,
    introText:
      'A rich and decadent dessert that combines the classic Tres Leches with a hint of coffee for an extra flavor boost.',
    description:
      'This Coffee Tres Leches cake is a delightful twist on the traditional dessert, featuring layers soaked in a coffee-infused milk mixture and topped with whipped cream and powdered cacao. It’s perfect for coffee lovers and those looking to try something new.',
    tags: {
      quick: false,
      easy: false,
      temperature: '',
      clean: false,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Flour',
        amount: 140,
        unit: 'g',
        flex: 'All-purpose flour',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Cacao powder',
        amount: 40,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Salt',
        amount: 0.75,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Baking soda',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Baking powder',
        amount: 2,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Brown sugar',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Milk',
        amount: 180,
        unit: 'ml',
        flex: 'Plant-based milk for a vegan option',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Yogurt or additional milk',
        amount: 60,
        unit: 'ml',
        flex: 'Plant-based yogurt or milk for a vegan option',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Apple cider vinegar',
        amount: 0.5,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vegetable oil',
        amount: 65,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Sweetened condensed milk',
        amount: 180,
        unit: 'ml',
        flex: 'Vegan condensed milk for a vegan option',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Milk (for soaking)',
        amount: 120,
        unit: 'ml',
        flex: 'Plant-based milk for a vegan option',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Coffee powder or espresso shot',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Whipped cream',
        amount: null,
        unit: '',
        flex: 'Vegan whipped cream for a vegan option',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Powdered cacao',
        amount: null,
        unit: '',
        flex: '',
        optional: true,
        topping: true,
        done: false,
      },
    ],
    instructions: [
      'Preheat the oven to 175°C (350°F).',
      'In a bowl, sift together the flour, cacao powder, salt, baking soda, and baking powder.',
      'In another bowl, mix the brown sugar, milk, yogurt (or additional milk), apple cider vinegar, and vegetable oil until well combined.',
      'Gradually add the dry ingredients to the wet ingredients and mix until smooth.',
      'Pour the batter into a greased baking pan and bake for 20 minutes, or until a toothpick inserted into the center comes out clean.',
      'Let the cake cool completely.',
      'In a separate bowl, mix the sweetened condensed milk, additional milk, and coffee powder or espresso shot.',
      'Once the cake is cool, poke holes all over the surface with a fork and slowly pour the coffee milk mixture over the cake, allowing it to soak in.',
      'Refrigerate the cake for at least 2 hours or overnight to allow the flavors to meld.',
      'Before serving, top with whipped cream and a dusting of powdered cacao.',
    ],
    notes: 'For a vegan option, use plant-based milk, yogurt, and whipped cream.',
  },
  //  Pesto Dressing
  {
    name: 'Pesto Dressing',
    param: 'pesto-dressing',
    recipeImage: '../assets/images/pesto-dressing.jpg',
    star: false,
    introText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Basil',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Walnuts',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any nuts will do just fine, and seeds are also a great option like sunflower seeds.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Nutritional yeast',
        amount: 0.25,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 1,
        unit: 'clove',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Olive oil',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Lemon juice',
        amount: 0.125,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Salt',
        amount: 0.5,
        unit: 'tsp',
        flex: 'Regular salt, black salt, or any other salt will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Black pepper',
        amount: 0.5,
        unit: 'tsp',
        flex: 'Any pepper will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Dijon mustard',
        amount: 0.5,
        unit: 'tbsp',
        flex: 'Or any other mustard.',
        optional: true,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
    notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  //  Southwest Dressing
  {
    name: 'Southwest Dressing',
    param: 'southwest-dressing',
    recipeImage: '../assets/images/southwest-dressing.jpg',
    star: false,
    introText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Water',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Cashews',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Lime',
        amount: 1,
        unit: '',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 2,
        unit: 'cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'BBQ sauce',
        amount: 0.25,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Salt',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Cumin',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Smoked paprika',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili powder',
        amount: 0.5,
        unit: 'tsp',
        flex: 'Any chili powder or flakes will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
    notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  //  Lemon Tahini Dressing
  {
    name: 'Lemon Tahini Dressing',
    param: 'lemon-tahini-dressing',
    recipeImage: '../assets/images/lemon-tahini-dressing.jpg',
    star: false,
    introText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Tahini',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Olive oil',
        amount: 0.125,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Water',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Lemon',
        amount: 0.25,
        unit: 'cup',
        flex: 'Yuzu, lime, or any other citrus will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 3,
        unit: 'cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Agave syrup',
        amount: 0.125,
        unit: 'cup',
        flex: 'Any sweetener will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Salt',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Dijon mustard',
        amount: 0.5,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
    notes: 'Try a 50/50 mix of lemon & yuzu.',
  },
  //  Chili Lime Dressing
  {
    name: 'Chili Lime Dressing',
    param: 'chili-lime-dressing',
    recipeImage: '../assets/images/chili-lime-dressing.jpg',
    star: false,
    introText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Tahini',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Water',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Lime',
        amount: 0.25,
        unit: 'cup',
        flex: 'Yuzu, lemon, or any other citrus will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 2,
        unit: 'cloves',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Agave syrup',
        amount: 0.125,
        unit: 'cup',
        flex: 'Any sweetener will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Salt',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili powder',
        amount: 0.5,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Smoked paprika',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
    notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  //  Sesame Ginger Dressing
  {
    name: 'Sesame Ginger Dressing',
    param: 'sesame-ginger-dressing',
    recipeImage: '../assets/images/sesame-ginger-dressing.jpg',
    star: false,
    introText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Sesame oil',
        amount: 0.25,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vegetable oil',
        amount: 0.25,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 0.25,
        unit: 'cup',
        flex: 'Any sweetener will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 0.25,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 0.25,
        unit: 'cup',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Ginger',
        amount: 0.125,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
    notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  //   Arancini
  {
    name: 'Arancini',
    param: 'arancini',
    recipeImage: '../assets/images/arancini.jpg',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: false,
      temperature: null,
      clean: false,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Burger
  {
    name: 'Burger',
    param: 'burger',
    recipeImage: '../assets/images/burger.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Garlic Noodles
  {
    name: 'Garlic Noodles',
    param: 'garlic-noodles',
    recipeImage: '../assets/images/ramen.png',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite noodle dish of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Hummus
  {
    name: 'Hummus',
    param: 'hummus',
    recipeImage: '../assets/images/hummus.jpg',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "Hummus is a delicious and nutritious spread made primarily from mashed chickpeas, tahini, olive oil, lemon juice, and garlic. It's a staple in Middle Eastern and Mediterranean cuisines and has gained global popularity due to its versatility and health benefits.",
    tags: {
      quick: true,
      easy: true,
      temperature: 400,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Chickpeas',
        amount: 400,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Roasted garlic',
        amount: 1,
        unit: '', // could specify unit or note it's one whole garlic
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Tahini',
        amount: 0.67,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Olive oil',
        amount: 4,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Black salt',
        amount: 1,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Lemon',
        amount: 1,
        unit: '', // could specify unit or note it's one whole lemon
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Smoked paprika',
        amount: null,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Fancy olive oil',
        amount: null,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
    ],
    instructions: [
      'Slice one full garlic in half and rub with olive oil.',
      'Roast garlic for one hour wrapped in foil or parchment paper.',
      'Add the remaining ingredients to a blender, then run until smooth.',
      'Make a spiral in the hummus and top with olive oil and smoked paprika.',
    ],
    notes: 'Include all the aquafaba for a super smooth hummus, otherwise just about half of the aquafaba.',
  },
  //   Ice cream
  {
    name: 'Ice Cream',
    param: 'ice-cream',
    recipeImage: '../assets/images/ice-cream.jpg',
    star: false,
    introText: 'My ice cream brings all the people to the yard.',
    description:
      'Ice cream is a frozen dessert made from a mixture of milk, cream, sugar, and flavorings. With an ice cream machine, you can easily make your own homemade ice cream and customize it to your liking. So grab a scoop and enjoy the creamy goodness of homemade ice cream.',
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Milk',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Cream',
        amount: 1,
        unit: 'cup',
        flex: 'Can be replaced with more milk, or half the amount with milk.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Xanthan gum',
        amount: 0.25,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Salt',
        amount: 0.25,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Fruit',
        amount: 0.5,
        unit: 'cup',
        flex: 'Or any other flavoring.',
        optional: true,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Add all the ingredients together in a bowl and mix.',
      'Add to your ice cream machine and let churn until done.',
    ],
    notes:
      'Add more sugar, replace the sugar with agave syrup/maple syrup/corn syrup, or even add alcohol like rum to make the ice cream more scoopable. Sugar and syrups prevent ice crystal formation and alcohol lowers the freezing point. A successful cornbread ice cream was made with 1.5 cup milk, 0.5 cup cream, 0.5 cup syrup, 0.25 tsp salt, and 0.5 cup polenta. It could have benefited from corn as well, blended with the milk in a high-speed mixer.',
  },
  //   Mirza Ghasemi
  {
    name: 'Mirza Ghasemi',
    param: 'mirza-ghasemi',
    recipeImage: '../assets/images/mirza-ghasemi.jpg',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Eggplant',
        amount: 2,
        unit: '',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Tomato',
        amount: 1,
        unit: 'cup',
        flex: 'Either crushed tomatoes, puréed tomatoes, whole canned tomatoes, or oven-roasted fresh tomatoes.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 1,
        unit: '',
        flex: 'Fresh garlic.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Salt',
        amount: 1,
        unit: 'tsp',
        flex: 'Black salt is preferable.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Pepper',
        amount: 1,
        unit: 'tsp',
        flex: "It don't matter if you're black or white🕺🏽.",
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Tomato paste',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Turmeric',
        amount: 1,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Add all ingredients to a pot and bring to a simmer on medium heat while stirring.',
      'When simmering, pour into ramekins or any other container like glasses and let cool for 30 min before storing in the fridge.',
      'Serve with any topping of your liking, like berries, coulis, nuts, or chocolate sauce.',
    ],
    notes: 'Serve with any bread. Rice, couscous, or quinoa are also great options.',
  },
  //   Pancakes
  {
    name: 'Pancakes',
    param: 'pancakes',
    recipeImage: '../assets/images/pancakes.jpg',
    star: true,
    introText: 'Swedish-style.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Flour',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: null,
        unit: '',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Milk',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Salt',
        amount: 0.25,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 0.5,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Baking powder',
        amount: 0.5,
        unit: 'tsp',
        flex: '0.5 parts baking soda.',
        optional: true,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Poké
  {
    name: 'Poké',
    param: 'poke',
    recipeImage: '../assets/images/poke.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Orange Tofu
  {
    name: 'Orange Tofu',
    param: 'orange-tofu',
    recipeImage: '../assets/images/orange-tofu.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: false,
      temperature: null,
      clean: false,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Panna Cotta
  {
    name: 'Panna Cotta',
    param: 'panna-cotta',
    recipeImage: '../assets/images/panna-cotta.jpg',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Milk',
        amount: 1,
        unit: 'cup',
        flex: 'Any plant-based milk will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Coconut milk',
        amount: 0.25,
        unit: 'cup',
        flex: "Cream works too, and is preferable if you don't desire any coconut flavor.",
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any sugar will do just fine, or even a liquid sweetener like maple syrup.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vanilla extract',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Agar agar',
        amount: 0.25,
        unit: 'tsp',
        flex: 'There are other gelling agents, but the amount you will need to add will differ.',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Add all ingredients to a pot and bring to a simmer on medium heat while stirring.',
      'When simmering, pour into ramekins or any other container like glasses and let cool for 30 min before storing in the fridge.',
      'Serve with any topping of your liking, like berries, coulis, nuts, or chocolate sauce.',
    ],
    notes: 'Angle the glasses while the Panna Cotta is cooling for a nice presentation.',
  },
  //   Ramen
  {
    name: 'Ramen',
    param: 'ramen',
    recipeImage: '../assets/images/ramen.png',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Root Vegetable Soup
  {
    name: 'Root Vegetable Soup',
    param: 'root-vegetable-soup',
    recipeImage: '../assets/images/root-vegetable-soup.jpg',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "Hummus is a delicious and nutritious spread made primarily from mashed chickpeas, tahini, olive oil, lemon juice, and garlic. It's a staple in Middle Eastern and Mediterranean cuisines and has gained global popularity due to its versatility and health benefits.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Potato',
        amount: 250,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Root sellery',
        amount: 250,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Carrot',
        amount: 250,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Parsnip',
        amount: 250,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Red lentils',
        amount: 1,
        unit: 'cup',
        flex: 'Faux meat or beans.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Water',
        amount: 1200,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Ketchup',
        amount: 0.5,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'White pepper',
        amount: 0.5,
        unit: 'tsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Dried oregano',
        amount: 4,
        unit: 'cloves',
        flex: 'Dried thyme, dried rosemary, or dried basil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Oil',
        amount: 1,
        unit: 'tbsp',
        flex: 'Any vegetable oil or butter works',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 1,
        unit: 'tbsp',
        flex: 'Hot sauce or chili paste.',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Vinegar',
        amount: 1,
        unit: 'tbsp',
        flex: 'Any vinegar.',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sourcream',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: true,
        topping: true,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 3,
        unit: 'cloves',
        flex: '',
        optional: true,
        topping: true,
        done: false,
      },
    ],
    instructions: [
      'Boil the pasta in salted water until al dente.',
      'Chop garlic and add to pan with oil on medium heat.',
      'After a minute, add tomato purée and sugar. Fry for 2 minutes.',
      'Add cream and sundried tomatoes, as well as any optional ingredients. Boil for 2 minutes.',
      'Add pasta to the sauce and mix. Serve with feta and basil.',
    ],
    notes:
      'Any root veggies go well in this dish, and any seasoning or sauce can be added for a different flavor profile.',
  },
  //   Swedish Balls
  {
    name: 'Swedish Balls',
    param: 'swedish-balls',
    recipeImage: '../assets/images/swedish-balls.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: false,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Tagine
  {
    name: 'Tagine',
    param: 'tagine',
    recipeImage: '../assets/images/tagine.png',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it. The soup is usually made with pieces of fried corn tortillas, which add a crunchy texture to the soup. It also features canned beans, and we add all the aquafaba that comes with it. The soup is often garnished with toppings such as diced avocado, cilantro, red onion, and sour cream. It is a satisfying and filling meal that is perfect for a cold day.',
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Water',
        amount: 600,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Puréed tomatoes',
        amount: 200,
        unit: 'ml',
        flex: 'We can use canned crushed tomatoes instead, or even chop up fresh tomatoes ourselves.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vegetable bouillon',
        amount: 2,
        unit: 'cubes',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Beans in aquafaba',
        amount: 400,
        unit: 'ml',
        flex: 'Kidney beans, great white beans, black beans, anything goes!',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Bell pepper',
        amount: 1,
        unit: '',
        flex: 'The bell pepper, corn, jackfruit, cilantro, and toppings can be substituted with anything. You can add more vegetables, but also add fewer vegetables than what we listed.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'BBQ sauce',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 1,
        unit: 'tbsp',
        flex: 'Or fresh chopped up chili if we have it. We often add a hot sauce instead, or a chili paste like Tobanjjan or tabasco.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Avocado',
        amount: 1,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Red onion',
        amount: 0.5,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Cilantro',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: true,
        topping: true,
        done: false,
      },
      {
        name: 'Ketchup',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Tortilla chips',
        amount: null,
        unit: '',
        flex: "This is added for crunch, so any chips fit. For example, we also love adding salt & vinegar chips, onion chips, BBQ chips, or if we don't have chips we may even go with roasted onion.",
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Oregano',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Corn',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Jackfruit',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Liquid smoke',
        amount: 2,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Lime',
        amount: 1,
        unit: '',
        flex: "Use lime, lemon, or yuzu, or we can use any vinegar in half the amount if we don't have citrus.",
        optional: false,
        topping: false,
        done: true,
      },
    ],
    instructions: [
      'We add all the ingredients except the toppings and lime to a pot and bring to a boil. The toppings are the avocado, red onion, and tortilla chips. Remember to add the aquafaba with the beans into the pot.',
      'While bringing the pot to a boil, we chop up the toppings.',
      'We boil on medium-high heat for about 5 min. We taste the soup during this time, and add more of any ingredient we wish.',
      'When it has finished boiling we add the lime, and we also bring some extra lime to the table for us to squeeze in as we desire.',
      'We serve the toppings in bowls on the table for each person to freely take.',
    ],
    notes:
      'This soup is slightly different each time we make it thanks to its versitility. Sometimes we also add plant-based melty cheese to it or plant-based sour cream with garlic.',
  },
  //   Thai Basil Sauce
  {
    name: 'Thai Basil Sauce',
    param: 'thai-basil-sauce',
    recipeImage: '../assets/images/thai-basil-sauce.jpg',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Thai basil',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Red bell pepper',
        amount: 0.5,
        unit: '',
        flex: 'Or another kind of bell pepper.',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 6,
        unit: 'cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vegan oyster sauce',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Dark soy sauce',
        amount: 1,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'tbsp',
        flex: 'Any sugar, or something like mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Yellow onion',
        amount: 0.5,
        unit: '',
        flex: 'Any onion will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 0.5,
        unit: 'tbsp',
        flex: 'Any chili flakes, hot sauce, or chili paste.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vegetable stock',
        amount: 1,
        unit: 'cup',
        flex: 'Vietnamese stock is nice for this one.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Corn starch',
        amount: 1,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Add all ingredients to a pot and bring to a simmer on medium heat while stirring.',
      'When simmering, pour into ramekins or any other container like glasses and let cool for 30 min before storing in the fridge.',
      'Serve with any topping of your liking, like berries, coulis, nuts, or chocolate sauce.',
    ],
    notes: 'Serve with any bread. Rice, couscous, or quinoa are also great options.',
  },
  //   Tomato Pasta
  {
    name: 'Tomato Pasta',
    param: 'tomato-pasta',
    recipeImage: '../assets/images/tomato-pasta.jpg',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "Hummus is a delicious and nutritious spread made primarily from mashed chickpeas, tahini, olive oil, lemon juice, and garlic. It's a staple in Middle Eastern and Mediterranean cuisines and has gained global popularity due to its versatility and health benefits.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Pasta',
        amount: 400,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Heavy cream',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Tomato purée',
        amount: 0.25,
        unit: 'cup',
        flex: 'Can be replaced with puréed tomatoes.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 4,
        unit: 'cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Olive oil',
        amount: 1,
        unit: 'tbsp',
        flex: 'Any vegetable oil works',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'tbsp',
        flex: 'Any sweetening agent works, like syrup, mirin, or brown sugar.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Sundried tomatoes',
        amount: 0.25,
        unit: 'cup',
        flex: 'Tapenade.',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 1,
        unit: 'tbsp',
        flex: 'Hot sauce or chili paste.',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Feta cheese',
        amount: null,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Basil',
        amount: null,
        unit: '',
        flex: 'Dried herbs work just as well.',
        optional: true,
        topping: true,
        done: false,
      },
    ],
    instructions: [
      'Boil the pasta in salted water until al dente.',
      'Chop garlic and add to pan with oil on medium heat.',
      'After a minute, add tomato purée and sugar. Fry for 2 minutes.',
      'Add cream and sundried tomatoes, as well as any optional ingredients. Boil for 2 minutes.',
      'Add pasta to the sauce and mix. Serve with feta and basil.',
    ],
    notes: 'Add a liquor like Vodka to the sauce to make the classic Penne alla Vodka.',
  },
  //   Tortilla Soup
  {
    name: 'Tortilla Soup',
    param: 'tortilla-soup',
    recipeImage: '../assets/images/tortilla-soup.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it. The soup is usually made with pieces of fried corn tortillas, which add a crunchy texture to the soup. It also features canned beans, and we add all the aquafaba that comes with it. The soup is often garnished with toppings such as diced avocado, cilantro, red onion, and sour cream. It is a satisfying and filling meal that is perfect for a cold day.',
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Water',
        amount: 600,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Puréed tomatoes',
        amount: 200,
        unit: 'ml',
        flex: 'We can use canned crushed tomatoes instead, or even chop up fresh tomatoes ourselves.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vegetable bouillon',
        amount: 2,
        unit: 'cubes',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Beans in aquafaba',
        amount: 400,
        unit: 'ml',
        flex: 'Kidney beans, great white beans, black beans, anything goes!',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Bell pepper',
        amount: 1,
        unit: '',
        flex: 'The bell pepper, corn, jackfruit, cilantro, and toppings can be substituted with anything. You can add more vegetables, but also add fewer vegetables than what we listed.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'BBQ sauce',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 1,
        unit: 'tbsp',
        flex: 'Or fresh chopped up chili if we have it. We often add a hot sauce instead, or a chili paste like Tobanjjan or tabasco.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Avocado',
        amount: 1,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Red onion',
        amount: 0.5,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Cilantro',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: true,
        topping: true,
        done: false,
      },
      {
        name: 'Ketchup',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Tortilla chips',
        amount: null,
        unit: '',
        flex: "This is added for crunch, so any chips fit. For example, we also love adding salt & vinegar chips, onion chips, BBQ chips, or if we don't have chips we may even go with roasted onion.",
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Oregano',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Corn',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Jackfruit',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Liquid smoke',
        amount: 2,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Lime',
        amount: 1,
        unit: '',
        flex: "Use lime, lemon, or yuzu, or we can use any vinegar in half the amount if we don't have citrus.",
        optional: false,
        topping: false,
        done: true,
      },
    ],
    instructions: [
      'We add all the ingredients except the toppings and lime to a pot and bring to a boil. The toppings are the avocado, red onion, and tortilla chips. Remember to add the aquafaba with the beans into the pot.',
      'While bringing the pot to a boil, we chop up the toppings.',
      'We boil on medium-high heat for about 5 min. We taste the soup during this time, and add more of any ingredient we wish.',
      'When it has finished boiling we add the lime, and we also bring some extra lime to the table for us to squeeze in as we desire.',
      'We serve the toppings in bowls on the table for each person to freely take.',
    ],
    notes:
      'This soup is slightly different each time we make it thanks to its versitility. Sometimes we also add plant-based melty cheese to it or plant-based sour cream with garlic.',
  },
];
