export const Recipes = [
  //   Arancini
  {
    name: 'Arancini',
    param: 'arancini',
    recipeImage: '../assets/images/arancini.jpg',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: false,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Burger
  {
    name: 'Burger',
    param: 'burger',
    recipeImage: '../assets/images/burger.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Garlic Noodles
  {
    name: 'Garlic Noodles',
    param: 'garlic-noodles',
    recipeImage: '../assets/images/ramen.png',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite noodle dish of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Poké
  {
    name: 'Poké',
    param: 'poke',
    recipeImage: '../assets/images/poke.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: true,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Orange Tofu
  {
    name: 'Orange Tofu',
    param: 'orange-tofu',
    recipeImage: '../assets/images/orange-tofu.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: false,
      temperature: null,
      clean: false,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Ramen
  {
    name: 'Ramen',
    param: 'ramen',
    recipeImage: '../assets/images/ramen.png',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Swedish Balls
  {
    name: 'Swedish Balls',
    param: 'swedish-balls',
    recipeImage: '../assets/images/swedish-balls.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      "This might just be our favorite soup of all time. A one-pot dish, super quick to make, no frying, just a bit of boiling, and the flexibility of the dish is on par with fried rice! You could put pretty much anything into the soup, and you can also choose any BBQ sauce of your liking or make one yourself with just 4 ingredients. Also, it's freakishly delicious and addictive.",
    tags: {
      quick: false,
      easy: false,
      temperature: null,
      clean: false,
      cheap: false,
    },
    ingredients: [
      {
        name: 'Noodles',
        amount: 200,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Butter',
        amount: 200,
        unit: 'g',
        flex: 'Neutral vegetable oil.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Garlic',
        amount: 8,
        unit: 'large cloves',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 1,
        unit: 'cup',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'cup',
        flex: 'White sugar, brown sugar, syrup, mirin.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 2,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Rice vinegar',
        amount: 2,
        unit: 'tbsp',
        flex: 'Any vinegar will do just fine.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Spring onion',
        amount: 3,
        unit: '',
        flex: 'Other crispy greens',
        optional: false,
        topping: false,
        done: false,
      },
    ],
    instructions: [
      'Bring a pot or pan of water to a boil, then salt the water to your liking and add the noodles.',
      'Slice the cloves of garlic.',
      'Add butter to a wok or pan on medium high heat and fry for 1 minute.',
      'Add soy, sugar, chili flakes, chopped spring onion, MSG, and vinegar. Set the heat to low until the noodles are done.',
      'Add noodles to the sauce, set the heat to high and mix for 1 minute. Serve.',
    ],
    notes: 'MSG is amazing in this dish.',
  },
  //   Tagine
  {
    name: 'Tagine',
    param: 'tagine',
    recipeImage: '../assets/images/tagine.png',
    star: false,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it. The soup is usually made with pieces of fried corn tortillas, which add a crunchy texture to the soup. It also features canned beans, and we add all the aquafaba that comes with it. The soup is often garnished with toppings such as diced avocado, cilantro, red onion, and sour cream. It is a satisfying and filling meal that is perfect for a cold day.',
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Water',
        amount: 600,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Puréed tomatoes',
        amount: 200,
        unit: 'ml',
        flex: 'We can use canned crushed tomatoes instead, or even chop up fresh tomatoes ourselves.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vegetable bouillon',
        amount: 2,
        unit: 'cubes',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Beans in aquafaba',
        amount: 400,
        unit: 'ml',
        flex: 'Kidney beans, great white beans, black beans, anything goes!',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Bell pepper',
        amount: 1,
        unit: '',
        flex: 'The bell pepper, corn, jackfruit, cilantro, and toppings can be substituted with anything. You can add more vegetables, but also add fewer vegetables than what we listed.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'BBQ sauce',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 1,
        unit: 'tbsp',
        flex: 'Or fresh chopped up chili if we have it. We often add a hot sauce instead, or a chili paste like Tobanjjan or tabasco.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Avocado',
        amount: 1,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Red onion',
        amount: 0.5,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Cilantro',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: true,
        topping: true,
        done: false,
      },
      {
        name: 'Ketchup',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Tortilla chips',
        amount: null,
        unit: '',
        flex: "This is added for crunch, so any chips fit. For example, we also love adding salt & vinegar chips, onion chips, BBQ chips, or if we don't have chips we may even go with roasted onion.",
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Oregano',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Corn',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Jackfruit',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Liquid smoke',
        amount: 2,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Lime',
        amount: 1,
        unit: '',
        flex: "Use lime, lemon, or yuzu, or we can use any vinegar in half the amount if we don't have citrus.",
        optional: false,
        topping: false,
        done: true,
      },
    ],
    instructions: [
      'We add all the ingredients except the toppings and lime to a pot and bring to a boil. The toppings are the avocado, red onion, and tortilla chips. Remember to add the aquafaba with the beans into the pot.',
      'While bringing the pot to a boil, we chop up the toppings.',
      'We boil on medium-high heat for about 5 min. We taste the soup during this time, and add more of any ingredient we wish.',
      'When it has finished boiling we add the lime, and we also bring some extra lime to the table for us to squeeze in as we desire.',
      'We serve the toppings in bowls on the table for each person to freely take.',
    ],
    notes:
      'This soup is slightly different each time we make it thanks to its versitility. Sometimes we also add plant-based melty cheese to it or plant-based sour cream with garlic.',
  },
  //   Tortilla Soup
  {
    name: 'Tortilla Soup',
    param: 'tortilla-soup',
    recipeImage: '../assets/images/tortilla-soup.jpg',
    star: true,
    introText:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
    description:
      'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it. The soup is usually made with pieces of fried corn tortillas, which add a crunchy texture to the soup. It also features canned beans, and we add all the aquafaba that comes with it. The soup is often garnished with toppings such as diced avocado, cilantro, red onion, and sour cream. It is a satisfying and filling meal that is perfect for a cold day.',
    tags: {
      quick: true,
      easy: true,
      temperature: null,
      clean: true,
      cheap: true,
    },
    ingredients: [
      {
        name: 'Water',
        amount: 600,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Puréed tomatoes',
        amount: 200,
        unit: 'ml',
        flex: 'We can use canned crushed tomatoes instead, or even chop up fresh tomatoes ourselves.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Vegetable bouillon',
        amount: 2,
        unit: 'cubes',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Beans in aquafaba',
        amount: 400,
        unit: 'ml',
        flex: 'Kidney beans, great white beans, black beans, anything goes!',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Bell pepper',
        amount: 1,
        unit: '',
        flex: 'The bell pepper, corn, jackfruit, cilantro, and toppings can be substituted with anything. You can add more vegetables, but also add fewer vegetables than what we listed.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'BBQ sauce',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'MSG',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Sugar',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Chili flakes',
        amount: 1,
        unit: 'tbsp',
        flex: 'Or fresh chopped up chili if we have it. We often add a hot sauce instead, or a chili paste like Tobanjjan or tabasco.',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Avocado',
        amount: 1,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Red onion',
        amount: 0.5,
        unit: '',
        flex: '',
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Cilantro',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: true,
        topping: true,
        done: false,
      },
      {
        name: 'Ketchup',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Light soy sauce',
        amount: 50,
        unit: 'ml',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Tortilla chips',
        amount: null,
        unit: '',
        flex: "This is added for crunch, so any chips fit. For example, we also love adding salt & vinegar chips, onion chips, BBQ chips, or if we don't have chips we may even go with roasted onion.",
        optional: false,
        topping: true,
        done: false,
      },
      {
        name: 'Oregano',
        amount: 1,
        unit: 'tbsp',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Corn',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: false,
        topping: false,
        done: false,
      },
      {
        name: 'Jackfruit',
        amount: 100,
        unit: 'g',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Liquid smoke',
        amount: 2,
        unit: 'tsp',
        flex: '',
        optional: true,
        topping: false,
        done: false,
      },
      {
        name: 'Lime',
        amount: 1,
        unit: '',
        flex: "Use lime, lemon, or yuzu, or we can use any vinegar in half the amount if we don't have citrus.",
        optional: false,
        topping: false,
        done: true,
      },
    ],
    instructions: [
      'We add all the ingredients except the toppings and lime to a pot and bring to a boil. The toppings are the avocado, red onion, and tortilla chips. Remember to add the aquafaba with the beans into the pot.',
      'While bringing the pot to a boil, we chop up the toppings.',
      'We boil on medium-high heat for about 5 min. We taste the soup during this time, and add more of any ingredient we wish.',
      'When it has finished boiling we add the lime, and we also bring some extra lime to the table for us to squeeze in as we desire.',
      'We serve the toppings in bowls on the table for each person to freely take.',
    ],
    notes:
      'This soup is slightly different each time we make it thanks to its versitility. Sometimes we also add plant-based melty cheese to it or plant-based sour cream with garlic.',
  },
];
