export const shakshuka = {
  name: 'Shakshuka',
  param: 'shakshuka',
  recipeImage: '../assets/images/shakshuka.jpg',
  star: false,
  introText: 'A hearty and flavorful dish with a spicy tomato sauce, perfect for breakfast or brunch.',
  description:
    'Shakshuka is a North African and Middle Eastern dish. It’s a one-pan meal that’s easy to make and packed with flavor. The sauce is made with tomatoes, bell peppers, onions, and spices, creating a rich and savory base for the eggs. Serve it with crusty bread for dipping.',
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Tomatoes',
      amount: 400,
      unit: 'g',
      flex: 'Canned whole, fresh, or crushed.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 25,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bell pepper',
      amount: 1,
      unit: '',
      flex: 'Any color.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 2,
      unit: 'cube',
      flex: '1 tsp salt',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 1,
      unit: 'tsp',
      flex: 'Any pepper works.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Bread',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Dice the potatoes, root celery, carrots, and parsnips into bite-sized pieces. Peel the vegetables if necessary.',
    'In a large pot, combine the diced vegetables, water, and bouillon. Bring to a boil over medium-high heat.',
    'Reduce the heat and simmer for 10 minutes.',
    'Stir in the lentils, ketchup, white pepper, dried oregano, chili (if using), and vinegar. Let it simmer for another 10 minutes to allow the flavors to meld.',
    'If you’d like a richer flavor, optionally serve with finely chopped garlic mixed with sour cream on top.',
    'Taste and adjust the seasoning as needed before serving.',
  ],
  notes:
    'This stew is versatile—you can swap out any root vegetables or add beans and faux meat for extra protein. For added depth, try roasting the vegetables before adding them to the pot. Adjust the spice level by increasing or decreasing the amount of chili or opting for a milder alternative.',
};
