export const sikilPak = {
  name: 'Sikil Pak',
  param: 'sikil-pak',
  recipeImage: 'assets/images/sikil-pak.jpg',
  star: false,
  introText: 'A traditional Yucatecan pumpkin seed dip with roasted tomatoes, habanero, and citrus.',
  description:
    'Sikil Pak is a vibrant Mayan dip from the Yucatán Peninsula made with toasted pumpkin seeds, charred tomatoes, and habanero. The seeds are ground into a creamy paste with garlic and onion, creating a rich, earthy dip with a kick of heat. Perfect with tortilla chips, tacos, or as a spread.',
  category: 'condiment',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Pumpkin seeds',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Habanero',
      amount: 1,
      unit: '',
      flex: 'Jalapeño, serrano, or any chili pepper',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 1,
      unit: '',
      flex: 'Any onion.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'If pumpkin seeds are not already roasted, toast them in a dry skillet over medium heat for 3-5 minutes, stirring frequently, until fragrant and lightly golden. Set aside to cool.',
    'Char the tomatoes, habanero, onion, and garlic. You can do this on a comal, in a dry skillet over high heat, or under a broiler, turning occasionally until blackened in spots and softened, about 8-10 minutes.',
    'Remove the stem from the habanero. For less heat, remove the seeds and membranes.',
    'In a blender or food processor, add the cooled pumpkin seeds and pulse until finely ground.',
    'Add the charred tomatoes, habanero, onion, garlic, and salt. Blend until smooth and creamy, scraping down the sides as needed.',
    'If the mixture is too thick, add a splash of water, 1 tablespoon at a time, until you reach your desired consistency.',
    'Taste and adjust salt as needed.',
  ],
  notes:
    'Traditionally served at room temperature. Store in an airtight container in the refrigerator for up to 3 days. The heat level depends on your pepper choice and whether you remove the seeds. For a smoky flavor, char the vegetables over an open flame.',
};
