export const southwestDressing = {
  name: 'Southwest Dressing',
  param: 'southwest-dressing',
  recipeImage: 'assets/images/southwest-dressing.jpg',
  star: false,
  introText: 'A creamy, smoky dressing with southwestern spices perfect for hearty salads and bowls.',
  description:
    'This rich southwest dressing combines cashews with bold southwestern flavors like cumin, smoked paprika, and chili powder. The addition of BBQ sauce gives it a unique smoky-sweet depth, while lime juice adds brightness. Perfect for taco salads, grain bowls, or as a dip for vegetables.',
  category: 'condiment',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Water',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cashews',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lime',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'BBQ sauce',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Smoked paprika',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili powder',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Any chili powder or flakes will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Soak cashews in hot water for 10 minutes to soften, then drain.',
    'Add all ingredients to a blender or food processor.',
    'Blend until smooth and creamy, about 2-3 minutes.',
    'If the dressing is too thick, add water 1 tablespoon at a time until desired consistency is reached.',
    'Taste and adjust seasoning with more lime juice, salt, or spices as needed.',
  ],
  notes: 'Soaking the cashews makes for a creamier texture. Adjust spice levels to your preference. Store in refrigerator for up to 1 week. Stir before using as ingredients may separate.',
};
