export const spongeCake = {
  name: 'Sponge Cake',
  param: 'sponge-cake',
  recipeImage: '../assets/images/sponge-cake.jpg',
  star: false,
  introText:
    'This light and fluffy vegan sponge cake is perfect for any occasion. Whether enjoyed plain or layered with fillings, it’s a simple yet delicious treat.',
  description:
    'This vegan sponge cake is soft, airy, and easy to make with just a few pantry staples. Using a combination of dairy-free milk, yogurt, and oil, it achieves a moist texture without the need for eggs. Perfect as a base for layered cakes, cupcakes, or simply enjoyed on its own with a dusting of powdered sugar.',
  tags: {
    quick: true,
    easy: true,
    temperature: '175',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'All-purpose flour',
      amount: 140,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bicarbonate of soda (baking soda)',
      amount: 0.125,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light brown sugar',
      amount: 75,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark brown sugar',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan yogurt',
      amount: 50,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable or light olive oil',
      amount: 60,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dairy-free milk',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C (fan) and grease or line a cake tin with parchment paper.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and both types of sugar.',
    'In a separate bowl, combine the vegan yogurt, oil, and dairy-free milk. Whisk until smooth.',
    'Gradually add the wet ingredients to the dry ingredients, stirring gently until just combined. Do not overmix.',
    'Pour the batter into the prepared cake tin and smooth the top.',
    'Bake for 18-20 minutes, or until a toothpick inserted into the center comes out clean.',
    'Allow the cake to cool in the tin for 5 minutes before transferring it to a wire rack to cool completely.',
  ],
  notes:
    'For added flavor, consider incorporating vanilla extract or lemon zest into the batter. This sponge cake can also be used as a base for layered cakes or cupcakes. Store in an airtight container at room temperature for up to 3 days, or refrigerate for longer freshness.',
};
