export const stickyBananaSpongePudding = {
  name: 'Sticky Banana Sponge Pudding',
  param: 'sticky-banana-sponge-pudding',
  recipeImage: 'assets/images/sticky-banana-sponge-pudding.jpg',
  star: false,
  introText:
    "This indulgent Sticky Banana Sponge Pudding combines the richness of ripe bananas with a luscious hazelnut toffee sauce for a dessert that's warm, comforting, and utterly irresistible.",
  description:
    'A moist and fluffy banana sponge topped with a decadent hazelnut toffee sauce, perfect for a cozy dessert on a chilly evening. This pudding is best enjoyed warm, with a scoop of your favorite ice cream.',
  tags: {
    quick: false,
    easy: true,
    temperature: '170',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Flour',
      amount: 360,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ripe bananas',
      amount: 3,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 4,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yoghurt',
      amount: 100,
      unit: 'g',
      flex: 'Any plant-based yoghurt',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 100,
      unit: 'ml',
      flex: 'Any neutral oil',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 360,
      unit: 'ml',
      flex: 'Any plant-based milk',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Apple cider vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'White vinegar or even citrus juice can be used as a substitute',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light brown sugar',
      amount: 250,
      unit: 'g',
      flex: 'Use dark brown sugar for a richer taste, or white sugar for a slightly lighter flavor',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Butter',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 120,
      unit: 'g',
      flex: 'Coconut cream can be used for a thicker consistency',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Hazelnut butter',
      amount: 80,
      unit: 'g',
      flex: 'Almond, pistachio, or peanut butter can be used instead',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Lightly grease a 9-inch square baking dish and preheat the oven to 170°C.',
    'Mix together the milk and apple cider vinegar, then set aside for at least 10 minutes to thicken and form a buttermilk-like consistency.',
    'Once thickened, pour the mixture into a large mixing bowl and add the bananas, dairy-free yoghurt, vegetable oil, and 150g of the light brown sugar.',
    "Sift in the flour, baking powder, bicarbonate of soda, and salt. Gently mix until just combined. It's okay if there are some small lumps.",
    'Pour the batter into the prepared baking dish and bake for 35-40 minutes, or until the sponge is well-risen and springs back when touched.',
    'While the sponge is baking, prepare the toffee sauce. In a saucepan, melt together the light brown sugar, dairy-free butter, and hazelnut butter over medium-high heat, stirring constantly until the mixture begins to bubble.',
    'Remove the saucepan from heat and carefully stir in the dairy-free double cream. Mix well and allow the sauce to cool and thicken.',
    'Once the sponge has cooled for about 10 minutes, poke holes into it using a chopstick or similar tool.',
    'Pour the toffee sauce over the sponge, ensuring it soaks into the holes. Allow the pudding to absorb the sauce for at least 20 minutes before serving.',
  ],
  notes:
    'This sticky pudding is great to serve with a scoop of ice cream on top while the pudding is still warm. For a nut-free version, you can replace the hazelnut butter with sunflower seed butter.',
};
