export const streuselBananaMuffins = {
  name: 'Streusel Banana Muffins',
  param: 'streusel-banana-muffins',
  recipeImage: 'assets/images/banana-muffins.jpg',
  star: false,
  introText: 'Banana muffins with a crunchy walnut streusel topping.',
  description:
    'These banana muffins are topped with a sweet, nutty streusel for extra texture and flavor. Perfect for breakfast or a snack!',
  category: 'dessert',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Bananas',
      amount: 2,
      unit: 'large',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flour',
      amount: 1.5,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Non-dairy milk',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    // Streusel topping
    {
      name: 'Flour',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Butter',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Walnuts',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 220°C and grease or line muffin tins with paper liners.',
    'In a large mixing bowl, whisk together the flour, baking powder, baking soda, salt, and the sugar. Mix it with a balloon whisk to prevent any flour lumps forming.',
    'In a separate bowl, combine the oil, milk, as well as vanilla extract and vinegar if using.',
    'Add the dry ingredients to the wet ingredients, stirring until just combined.',
    'Pour the batter into the prepared muffin liners, filling them about 2/3 full.',
    'For the streusel: In a small bowl, combine flour, brown sugar, and salt. Add cold butter cubes and rub with your fingers or a fork until crumbly. Stir in walnuts.',
    'Sprinkle the streusel evenly over the muffin batter.',
    'Bake for 20 minutes if using small muffin ramekins, 26 min if using large muffin ramekins, or until a toothpick inserted into the center comes out clean. Decrease the temperature to 175°C after 5-7 minutes.',
    'Allow the muffins to cool in the tin for 20 minutes before serving.',
    'Bake for 20-25 minutes, or until a toothpick inserted into the center comes out clean.',
    'Let cool before serving.',
  ],
  notes: 'For extra crunch, add more walnuts to the streusel.',
};
