export const waffles = {
  name: 'Waffles',
  param: 'waffles',
  recipeImage: '../assets/images/waffles.jpg',
  star: false,
  introText: 'These light and crispy vegan waffles are perfect for a cozy breakfast or brunch.',
  description:
    'Golden, crispy, and fluffy, these vegan waffles are made with simple ingredients and are easy to prepare. Whether served with syrup, fresh fruits, or vegan whipped cream, they are sure to become a family favorite.',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Butter',
      amount: 40,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 20,
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Flour',
      amount: 80,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 0.25,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a medium-sized bowl, whisk together the flour, baking powder, sugar, and salt.',
    'In a small saucepan or microwave-safe bowl, melt the vegan butter and let it cool slightly.',
    'In a separate bowl, mix the melted butter and plant-based milk until well combined.',
    'Gradually pour the wet ingredients into the dry ingredients, whisking until a smooth batter forms. Be careful not to overmix.',
    'Preheat your waffle iron according to the manufacturer’s instructions.',
    'Lightly grease the waffle iron with oil or vegan butter if necessary.',
    'Pour an appropriate amount of batter onto the waffle iron and cook until golden brown and crispy, following your waffle maker’s guidelines.',
    'Carefully remove the waffles and repeat with the remaining batter.',
    'Serve warm with your favorite toppings like maple syrup, fresh fruits, or vegan whipped cream.',
  ],
  notes:
    'For a crispier texture, allow the waffles to cool on a wire rack for a few minutes before serving. You can also make these waffles in advance and reheat them in a toaster or oven for a quick breakfast.',
};
