export const chiliLimeDressing = {
  name: 'Chili Lime Dressing',
  param: 'chili-lime-dressing',
  recipeImage: 'assets/images/chili-lime-dressing.jpg',
  star: false,
  introText: 'A zesty tahini-based dressing with a spicy kick perfect for salads and grain bowls.',
  description:
    'This vibrant chili lime dressing combines creamy tahini with bright citrus and warming spices. The combination of chili powder and smoked paprika gives it a smoky heat, while lime juice adds brightness. Perfect for drizzling over salads, roasted vegetables, or grain bowls.',
  category: 'condiment',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Tahini',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lime',
      amount: 0.25,
      unit: 'cup',
      flex: 'Yuzu, lemon, or any other citrus will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 2,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Agave syrup',
      amount: 0.125,
      unit: 'cup',
      flex: 'Any sweetener will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 0.5,
      unit: 'tbsp',
      flex: 'Any chili flakes, powder, or even sauce or fresh chili will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Smoked paprika',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Add all ingredients to a blender or food processor.',
    'Blend until smooth and creamy, about 1-2 minutes.',
    'If the dressing is too thick, add water 1 tablespoon at a time until desired consistency is reached.',
    'Taste and adjust seasoning with more salt, lime juice, or chili powder as needed.',
  ],
  notes: 'Start with less chili powder and add more to taste. This dressing thickens when chilled. Store in refrigerator for up to 1 week. Stir before using as ingredients may separate.',
};
