export const chocolateTea = {
  name: 'Chocolate Tea',
  param: 'chocolate-tea',
  recipeImage: 'assets/images/chocolate-tea.jpg',
  star: false,
  introText: 'A warm, spiced chocolate drink with cinnamon.',
  description:
    'A cozy and comforting hot beverage that combines rich chocolate with aromatic cinnamon. Simple to make with just a few ingredients, this chocolate tea is perfect for chilly days or as a sweet treat any time.',
  category: 'drinks',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Chocolate',
      amount: 25,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon stick',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Bring the water to a boil in a small saucepan.',
    'Add the cinnamon stick and let it simmer for a couple of minutes.',
    'Chop or break the chocolate into small pieces and add to the pot.',
    'Stir until the chocolate is fully melted and combined.',
    'Add the brown sugar and stir until dissolved.',
    'Remove the cinnamon stick and pour into cups. Serve hot.',
  ],
  notes:
    'You can use dark, milk, or semi-sweet chocolate depending on your preference. For a richer drink, replace some of the water with milk. Adjust the sugar to taste.',
};
