export const cigKofte = {
  name: 'Çiğ Köfte',
  param: 'cig-kofte',
  recipeImage: 'assets/images/cig-kofte.jpg',
  star: false,
  introText: 'Spiced bulgur patties kneaded by hand, wrapped in lettuce 🇹🇷.',
  description:
    'A Turkish 🇹🇷 street-food classic in its popular meatless form. Fine bulgur is softened, then kneaded for a long time with tomato and red pepper paste, isot, garlic, and a tangle of warm spices until it turns dark, soft, and deeply savoury. Brightened with lemon and pomegranate molasses and finished with parsley and spring onion, the mixture is squeezed into the signature finger-grooved ovals and served cold, wrapped in crisp lettuce. The long kneading is what makes or breaks the texture.',
  category: 'side',
  tags: {
    quick: false,
    easy: false,
    temperature: 'cold',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Fine bulgur',
      amount: 2,
      unit: 'cups',
      flex: 'Köftelik bulgur, the smallest grind.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Hot water',
      amount: 1.5,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 1,
      unit: '',
      flex: 'Grated or very finely chopped.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato paste',
      amount: 4,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red pepper paste',
      amount: 2,
      unit: 'tbsp',
      flex: 'Biber salçası.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red pepper flakes',
      amount: 4,
      unit: 'tbsp',
      flex: 'Pul biber or isot, to taste.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon',
      amount: 1,
      unit: 'tsp',
      flex: 'Traditional, adds warmth.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: 'Crushed.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 2,
      unit: '',
      flex: 'Juice of 2 lemons.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Pomegranate molasses',
      amount: 4,
      unit: 'tbsp',
      flex: 'Nar ekşisi.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Olive oil',
      amount: 4,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Parsley',
      amount: 1,
      unit: 'bunch',
      flex: 'Finely chopped.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Spring onions',
      amount: 4,
      unit: '',
      flex: 'Finely chopped.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: 'To taste.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lettuce leaves',
      amount: 1,
      unit: 'head',
      flex: 'For wrapping.',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Lemon wedges',
      amount: 1,
      unit: '',
      flex: 'To serve.',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Put the bulgur in a large bowl, pour over the hot water, cover, and let it sit for about 15 minutes until softened.',
    'Add the tomato paste, red pepper paste, pepper flakes, cumin, black pepper, cinnamon, garlic, and salt.',
    'Knead hard with your hands for 10 to 15 minutes until the mixture darkens, softens, and comes together. This step is what makes the texture.',
    'Work in the grated onion, lemon juice, pomegranate molasses, and olive oil, kneading until smooth and slightly sticky. Add a splash of water if it feels too dry.',
    'Mix in the parsley and spring onions last.',
    'Squeeze portions in your fist to form ridged ovals with the classic finger grooves.',
    'Chill for 30 minutes, then serve wrapped in lettuce with a squeeze of lemon.',
  ],
  notes:
    'Isot (Urfa pepper) gives the most authentic deep, smoky heat. Kneading time is essential, so do not rush it. This is the modern meatless version; the raw-meat original is rarely made commercially. Drizzle extra pomegranate molasses over before wrapping for a sharper finish.',
};
