export const coffeeTresLeches = {
  name: 'Coffee Tres Leches',
  param: 'coffee-tres-leches',
  recipeImage: 'assets/images/coffee-tres-leches.jpg',
  star: false,
  introText:
    'A rich and decadent dessert that combines the classic Tres Leches with a hint of coffee for an extra flavor boost.',
  description:
    'This Coffee Tres Leches cake is a delightful twist on the traditional dessert, featuring layers soaked in a coffee-infused milk mixture and topped with whipped cream and powdered cacao. It’s perfect for coffee lovers and those looking to try something new.',
  category: 'dessert',
  tags: {
    quick: false,
    easy: false,
    temperature: '',
    clean: false,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Flour',
      amount: 140,
      unit: 'g',
      flex: 'All-purpose flour',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cacao powder',
      amount: 40,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.75,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking soda',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Baking powder',
      amount: 2,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk',
      amount: 180,
      unit: 'ml',
      flex: 'Plant-based milk for a vegan option',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yogurt or additional milk',
      amount: 60,
      unit: 'ml',
      flex: 'Plant-based yogurt or milk for a vegan option',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Apple cider vinegar',
      amount: 0.5,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 65,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sweetened condensed milk',
      amount: 180,
      unit: 'ml',
      flex: 'Vegan condensed milk for a vegan option',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Milk (for soaking)',
      amount: 120,
      unit: 'ml',
      flex: 'Plant-based milk for a vegan option',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Coffee powder or espresso shot',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Whipped cream',
      amount: null,
      unit: '',
      flex: 'Vegan whipped cream for a vegan option',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Powdered cacao',
      amount: null,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Preheat the oven to 175°C (350°F).',
    'In a bowl, sift together the flour, cacao powder, salt, baking soda, and baking powder.',
    'In another bowl, mix the brown sugar, milk, yogurt (or additional milk), apple cider vinegar, and vegetable oil until well combined.',
    'Gradually add the dry ingredients to the wet ingredients and mix until smooth.',
    'Pour the batter into a greased baking pan and bake for 20 minutes, or until a toothpick inserted into the center comes out clean.',
    'Let the cake cool completely.',
    'In a separate bowl, mix the sweetened condensed milk, additional milk, and coffee powder or espresso shot.',
    'Once the cake is cool, poke holes all over the surface with a fork and slowly pour the coffee milk mixture over the cake, allowing it to soak in.',
    'Refrigerate the cake for at least 2 hours or overnight to allow the flavors to meld.',
    'Before serving, top with whipped cream and a dusting of powdered cacao.',
  ],
  notes: 'For a vegan option, use plant-based milk, yogurt, and whipped cream.',
};
