export const hummus = {
  name: 'Hummus',
  param: 'hummus',
  recipeImage: 'assets/images/hummus.jpg',
  star: false,
  introText:
    'A creamy and flavorful Middle Eastern spread made from chickpeas, tahini, olive oil, lemon juice, and garlic.',
  description:
    "Hummus is a delicious and nutritious spread made primarily from mashed chickpeas, tahini, olive oil, lemon juice, and garlic. It's a staple in Middle Eastern and Mediterranean cuisines and has gained global popularity due to its versatility and health benefits.",
  category: 'side',
  tags: {
    quick: true,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Chickpeas including aquafaba',
      amount: 400,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tahini',
      amount: 0.67,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 4,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black salt',
      amount: 1,
      unit: 'tsp',
      flex: 'Any salt',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon',
      amount: 1,
      unit: '',
      flex: 'Lime',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Roasted garlic',
      amount: 1,
      unit: 'head',
      flex: '1-2 raw cloves of garlic',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Smoked paprika',
      amount: null,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Olive oil',
      amount: null,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Slice one full garlic in half and rub with oil.',
    'Roast garlic for one hour at 200°C (400°F) wrapped in foil or parchment paper.',
    'Add the ingredients to a blender including the roasted garlic which we can squeeze out of the skin, then blend until smooth.',
    'Serve on a plate or in a bowl. Make a spiral in the hummus and top with olive oil and smoked paprika.',
  ],
  notes: 'Include all the aquafaba for a super smooth hummus, otherwise just about half of the aquafaba.',
};
