export const lemongrassSoup = {
  name: 'Lemongrass Soup',
  param: 'lemongrass-soup',
  recipeImage: 'assets/images/lemongrass-soup.png',
  star: false,
  introText: 'Bright, aromatic broth with lemongrass, ginger, and mushrooms finished with lemon and cilantro.',
  description:
    'A fragrant, restorative soup built on lemongrass, ginger, and chilies. Shiitake mushrooms add body, vegan fish sauce brings savory depth, and a touch of brown sugar balances the lively lemon. Add tofu for protein or enjoy it as a light, comforting broth.',
  category: 'soup',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Vegetable oil',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Shallots',
      amount: 4,
      unit: '',
      flex: 'Any onion works.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 2,
      unit: '',
      flex: 'Any chili flakes, dried whole chilies, or fresh chilies.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemongrass',
      amount: 2,
      unit: 'stems',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ginger',
      amount: 2,
      unit: 'cm',
      flex: 'Galangal.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Shiitake mushrooms',
      amount: 8,
      unit: 'pcs',
      flex: 'Any mushrooms like button or oyster mushrooms.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable broth',
      amount: 8,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegan fish sauce (nam pla)',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Brown sugar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any sugar or sweetener.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon zest',
      amount: 1.5,
      unit: 'tsp',
      flex: 'Lime zest.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 0.25,
      unit: 'cup',
      flex: 'Lime juice.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cilantro',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Tofu',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Prep aromatics: Trim and bruise the lemongrass (cut into 5 cm pieces). Thinly slice the ginger, shallots, and garlic. Slice the shiitakes.',
    'Heat the vegetable oil in a pot over medium heat. Add shallots and cook 2–3 minutes until translucent. Add garlic, chili flakes, and black pepper; cook 30–60 seconds until fragrant.',
    'Add lemongrass and ginger; cook 1 minute, stirring. Add the sliced shiitakes and sauté 2–3 minutes until slightly softened.',
    'Pour in the vegetable broth. Bring to a boil, then lower to a gentle simmer for 10–12 minutes to infuse flavors.',
    'Stir in vegan fish sauce and brown sugar. Simmer 2 minutes. If using tofu, add now and warm through 2–3 minutes.',
    'Remove from heat. Stir in lemon zest and lemon juice. Taste and adjust with more vegan fish sauce, lemon juice, or sugar to balance.',
    'Serve hot, garnished with chopped cilantro. Optionally remove lemongrass pieces before serving.',
  ],
  notes:
    'For a more traditional Thai profile, add kaffir lime leaves if available. Adjust heat with more or fewer chili flakes. Add-ins like tofu, baby corn, or bok choy work well. Leftovers keep up to 3 days chilled; reheat gently and add a splash of water if needed.',
};
