export const lentilStew = {
  name: 'Lentil Stew',
  param: 'lentil-stew',
  recipeImage: 'assets/images/lentil-stew.jpg',
  star: false,
  introText: 'This hearty lentil stew combines a rich blend of spices, aromatic vegetables, and a hint of citrus.',
  description:
    'Warm, spiced, and deeply satisfying, this lentil stew is a fantastic vegan meal that packs a punch of flavor. The combination of caramelized onions, earthy lentils, and the bright acidity from lemon juice and pickled jalapeños makes it a standout dish. Ideal for cozy dinners, this stew is both nutritious and delicious.',
  category: ['main', 'soup'],
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Onions',
      amount: 2,
      unit: 'large',
      flex: 'Red onions for a sweeter flavor, or shallots for a milder taste',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any sweetener of choice',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Carrots',
      amount: 2,
      unit: 'medium',
      flex: 'Parsnips or sweet potatoes can be used',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Celery',
      amount: 2,
      unit: 'stalks',
      flex: 'Fennel for a slightly different flavor profile',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Lentils',
      amount: 1,
      unit: 'cup',
      flex: 'Green or brown lentils for a firmer texture; red lentils for a softer texture',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable bouillon',
      amount: 2,
      unit: 'cubes',
      flex: 'Vegetable broth powder or liquid broth can be used instead',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 1.2,
      unit: 'liters',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ketchup',
      amount: 0.25,
      unit: 'cup',
      flex: 'Tomato paste with a bit of vinegar and sugar can substitute',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Tomato purée',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark soy sauce',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Jalapeños',
      amount: 0.25,
      unit: 'cup',
      flex: 'Pickled jalapeños, fresh jalapeños, chili flakes, or any hot sauce',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Pickle juice',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cinnamon',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'MSG',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 2,
      unit: 'tbsp',
      flex: 'Lime or yuzu juice for a slightly different citrus note',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Preserved lemons',
      amount: 2,
      unit: '',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a large pot, heat a bit of oil over medium heat. Add the sliced onions and cook, stirring occasionally, until caramelized, about 10-15 minutes.',
    'Sprinkle in the sugar and white pepper, stirring to combine. Let the sugar melt and slightly caramelize with the onions.',
    'Add the chopped carrots and celery to the pot and sauté for another 5 minutes until the vegetables begin to soften.',
    'Stir in the lentils, bouillon cubes, and water. Bring to a boil, then reduce the heat and let it simmer for 25-30 minutes, or until the lentils are tender.',
    'Mix in the ketchup, tomato purée, dark soy sauce, pickled jalapeños, pickle juice, cinnamon, MSG, and cumin. Let the stew simmer for an additional 10 minutes, allowing the flavors to meld together.',
    'Finally, stir in the lemon juice and chopped preserved lemons (if using). Taste and adjust seasoning as necessary.',
    'Serve the stew hot, garnished with fresh herbs if desired. It can be stored in the fridge for up to 4 days or frozen for later use.',
  ],
  notes:
    'For an extra layer of flavor, consider adding a splash of red wine while sautéing the vegetables. This stew is incredibly versatile and can be customized by varying the vegetables or adding different spices according to your taste.',
};
