export const mangoChutnyCurry = {
  name: 'Mango Chutney Curry',
  param: 'mango-chutney-curry',
  recipeImage: 'assets/images/mango-chutney-curry.jpg',
  star: false,
  introText: 'A creamy, lightly sweet curry with mango chutney, coconut cream, and plenty of greens and beans.',
  description:
    "This mango chutney curry is a quick, flavorful one-pot meal. Caramelized onions form a rich base, while curry powder and sambal oelek bring warmth and heat. Mango chutney and coconut cream create a luscious, slightly sweet sauce that ties everything together. Loaded with edamame, white beans, and spinach, it's hearty and satisfying served over rice.",
  category: ['main'],
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Rice',
      amount: null,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Edamame beans',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White beans',
      amount: 1,
      unit: 'can',
      flex: 'Cannellini or butter beans',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Curry powder',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sambal oelek',
      amount: 1,
      unit: 'tbsp',
      flex: 'Chili paste or sriracha',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mango chutney',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Coconut cream',
      amount: 1,
      unit: 'can',
      flex: 'Coconut milk or cream',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Spinach',
      amount: 50,
      unit: 'g',
      flex: 'Kale or chard',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Cook the rice your way.',
    'Slice the onion and caramelize it in a large pan with butter over medium heat.',
    'Add the curry powder and sambal oelek to the caramelized onion and stir for 1 minute until fragrant.',
    'Pour in the coconut cream and mango chutney. Stir to combine and bring to a gentle simmer.',
    'Drain the white beans. Add them along with the edamame beans to the pan.',
    'Stir in the light soy sauce and let everything simmer for 5 minutes.',
    'Add the spinach and stir until wilted, about 1-2 minutes.',
    'Serve the curry over rice.',
  ],
};
