export const peanutNoodles = {
  name: 'Peanut Noodles',
  param: 'peanut-noodles',
  recipeImage: 'assets/images/peanut-noodles.jpg',
  star: false,
  introText: 'Creamy, savory-sweet peanut sauce tossed with bouncy noodles and finished with scallions and sesame.',
  description:
    'Quick weeknight noodles coated in a silky peanut sauce made with soy sauce, dark soy, crispy chili oil, vinegar, and a touch of sugar. Pasta water loosens and emulsifies the sauce so it clings to every strand. Top with scallions and sesame seeds for crunch and freshness.',
  category: ['main'],
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Noodles',
      amount: 2,
      unit: 'servings',
      flex: 'Any noodles (ramen, wheat, udon, spaghetti).',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Peanut butter',
      amount: 3,
      unit: 'tbsp',
      flex: 'Smooth or crunchy. Tahini or almond butter works too.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Light soy',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dark soy',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Crispy chili oil',
      amount: 2,
      unit: 'tbsp',
      flex: 'Vegetable oil or chili oil combined with chili flakes',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Pasta water',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallions',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Cook noodles in salted water according to package directions. Reserve at least 1 cup pasta water, then drain.',
    'In a large bowl, whisk together peanut butter, soy sauce, dark soy, crispy chili oil, vinegar, and sugar until smooth.',
    'Slowly whisk in 1/3–1/2 cup hot pasta water until the sauce is glossy and pourable.',
    'Add drained noodles to the bowl and toss vigorously to coat, adding more pasta water as needed so the sauce clings.',
    'Top with scallions and sesame seeds. Serve immediately.',
  ],
  notes:
    'Thin the sauce with extra pasta water if it tightens up. Great with add-ins like shredded cucumber, blanched greens, edamame, or tofu.',
};
