export const pesto = {
  name: 'Pesto',
  param: 'pesto',
  recipeImage: 'assets/images/pesto.jpg',
  star: false,
  introText: 'A versatile and flavorful sauce made from fresh basil, perfect for pasta, sandwiches, and more.',
  description:
    'This pesto recipe is a delicious and easy-to-make sauce that can be used in a variety of dishes. It features fresh basil, nuts, and nutritional yeast for a rich, cheesy flavor without the dairy.',
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Fresh basil',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Walnuts',
      amount: 4,
      unit: 'tbsp',
      flex: 'If nut-free, try sunflower seeds',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Nutritional yeast',
      amount: 3,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: 'Use black salt for a unique flavor, adjust to taste',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Olive oil',
      amount: 4,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'In a food processor, add the fresh basil, nuts (or seeds), and garlic. Pulse until finely chopped.',
    'Add the lemon juice, nutritional yeast, and salt to the food processor.',
    'With the processor running, slowly drizzle in the olive oil until the mixture is well combined and smooth. You can adjust the consistency by adding more oil if needed.',
    'Taste and adjust the seasoning, adding more salt, nutritional yeast, or lemon juice as desired.',
    'Use immediately or store in an airtight container in the refrigerator for up to a week.',
  ],
  notes:
    'This pesto is incredibly versatile; you can experiment with different nuts, seeds, or even add a bit of vegan Parmesan for extra richness. For a nut-free option, sunflower seeds work great!',
};
