export const pestoDressing = {
  name: 'Pesto Dressing',
  param: 'pesto-dressing',
  recipeImage: 'assets/images/pesto-dressing.jpg',
  star: false,
  introText: 'A fresh, herbaceous dressing that brings classic pesto flavors to any salad.',
  description:
    'This vibrant pesto dressing transforms traditional basil pesto into a lighter, more versatile dressing. With fresh basil, nuts, nutritional yeast, and garlic blended with olive oil and lemon juice, it delivers all the aromatic flavors of pesto in a pourable form perfect for salads and vegetables.',
  tags: {
    quick: false,
    easy: true,
    temperature: null,
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Basil',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Walnuts',
      amount: 2,
      unit: 'tbsp',
      flex: 'Any nuts will do just fine, and seeds are also a great option like sunflower seeds.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Nutritional yeast',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 1,
      unit: 'clove',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lemon juice',
      amount: 0.125,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Regular salt, black salt, or any other salt will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Black pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: 'Any pepper will do just fine.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dijon mustard',
      amount: 0.5,
      unit: 'tbsp',
      flex: 'Or any other mustard.',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Add all ingredients except the oil to a blender or food processor.',
    'Pulse a few times to roughly chop, then slowly drizzle in oil while blending.',
    'Blend until smooth and creamy, about 1-2 minutes.',
  ],
  notes: 'Taste and adjust seasoning with more salt, lemon juice, or nutritional yeast as needed. Store in refrigerator for up to 1 week. Stir before using as ingredients may separate. The dressing will darken slightly when stored but remains delicious.',
};
