export const pozole = {
  name: 'Pozole',
  param: 'pozole',
  recipeImage: 'assets/images/pozole.jpg',
  star: false,
  introText: 'A hearty Mexican soup with hominy, vegetables, and aromatic spices.',
  description:
    'This traditional Mexican soup features tender hominy kernels in a rich, flavorful broth with vegetables and warming spices. Pozole is a celebration dish that brings families together, often served during special occasions and holidays. The soup is traditionally topped with fresh garnishes like radishes, lettuce, and lime, allowing each person to customize their bowl to their taste.',
  category: ['main', 'soup'],
  tags: {
    quick: false,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Hominy',
      amount: 2,
      unit: 'cans',
      flex: 'Chickpeas or any other pea or bean.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable broth',
      amount: 6,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 2,
      unit: 'tbsp',
      flex: 'Any chili, chili flakes, or chili sauce.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Bay leaf',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cumin',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Radish',
      amount: 4,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Lettuce',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Lime',
      amount: 2,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Fresh oregano',
      amount: 2,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Avocado',
      amount: 1,
      unit: '',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Dice the onion and mince the garlic.',
    'Heat a large pot over medium heat and sauté the onion for 5 minutes until translucent.',
    'Add the garlic and cook for another minute until fragrant.',
    'Add the vegetable broth, chili, drained hominy, bay leaves, cumin, and salt.',
    'Bring to a boil, then reduce heat and simmer for 30 minutes.',
    'Taste and adjust seasoning with more salt if needed.',
    'Remove bay leaves before serving.',
    'Serve hot with thinly sliced radishes, shredded lettuce, lime wedges, avocado, and fresh oregano on the side.',
  ],
  notes:
    'The soup tastes even better the next day as the flavors continue to develop. Traditional garnishes are essential - they add freshness and crunch that balance the rich, warming broth. This soup freezes well for up to 3 months. Additional salsa of any kind can be added to the soup as well for extra flavor and heat.',
};
