export const rootVegetableSoup = {
  name: 'Root Vegetable Soup',
  param: 'root-vegetable-soup',
  recipeImage: '../assets/images/root-vegetable-soup.jpg',
  star: false,
  introText:
    'A hearty and flavorful soup that originated in Mexico. A one-pot dish ready in just 15 minutes and we can add just about anything in it.',
  description:
    "Hummus is a delicious and nutritious spread made primarily from mashed chickpeas, tahini, olive oil, lemon juice, and garlic. It's a staple in Middle Eastern and Mediterranean cuisines and has gained global popularity due to its versatility and health benefits.",
  tags: {
    quick: true,
    easy: true,
    temperature: null,
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Potato',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Root sellery',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Carrot',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Parsnip',
      amount: 250,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Red lentils',
      amount: 1,
      unit: 'cup',
      flex: 'Faux meat or beans.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Water',
      amount: 1200,
      unit: 'ml',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Ketchup',
      amount: 0.5,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'White pepper',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Dried oregano',
      amount: 4,
      unit: 'cloves',
      flex: 'Dried thyme, dried rosemary, or dried basil.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Oil',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any vegetable oil or butter works',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Chili flakes',
      amount: 1,
      unit: 'tbsp',
      flex: 'Hot sauce or chili paste.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Vinegar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any vinegar.',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Sourcream',
      amount: 1,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 3,
      unit: 'cloves',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
  ],
  instructions: [
    'Boil the pasta in salted water until al dente.',
    'Chop garlic and add to pan with oil on medium heat.',
    'After a minute, add tomato purée and sugar. Fry for 2 minutes.',
    'Add cream and sundried tomatoes, as well as any optional ingredients. Boil for 2 minutes.',
    'Add pasta to the sauce and mix. Serve with feta and basil.',
  ],
  notes:
    'Any root veggies go well in this dish, and any seasoning or sauce can be added for a different flavor profile.',
};
