export const serranoSalsa = {
  name: 'Serrano Salsa',
  param: 'serrano-salsa',
  recipeImage: 'assets/images/serrano-salsa.jpg',
  star: false,
  introText: 'A spicy and flavorful salsa with a kick of heat from fresh serrano peppers.',
  description:
    'This vibrant serrano salsa brings serious heat and flavor to any dish. The sautéed vegetables create a rich, complex base while the fresh cilantro adds brightness. Perfect for tacos, grilled meats, or as a spicy condiment for any Mexican-inspired meal.',
  category: ['condiment'],
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Serrano pepper',
      amount: 1,
      unit: '',
      flex: 'Any chili pepper.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Salt',
      amount: 0.5,
      unit: 'tsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 1,
      unit: 'clove',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Yellow onion',
      amount: 0.25,
      unit: '',
      flex: 'White onion, shallot.',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable oil',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Fresh cilantro',
      amount: 0.25,
      unit: 'cup',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Roughly chop the serrano pepper, garlic clove, and yellow onion into pieces that will fit in your blender.',
    'Heat the vegetable oil in a small skillet over medium heat.',
    'Add the chopped serrano, garlic, and onion to the hot oil.',
    'Sauté the vegetables for 3-4 minutes until they begin to soften and become fragrant. The onion should be translucent.',
    'Remove from heat and let cool for a minute or two.',
    'Transfer the sautéed vegetables and oil to a blender.',
    'Add the salt and fresh cilantro (if using) to the blender.',
    'Blend on high speed until smooth and well combined, about 30-60 seconds.',
    'Taste and adjust seasoning with additional salt if needed.',
    'Serve immediately or store in the refrigerator for up to one week.',
  ],
  notes:
    'This salsa packs serious heat! Start with half a serrano if you prefer milder spice levels. The oil helps carry the flavors and creates a smooth consistency. For a chunkier texture, pulse the blender instead of blending continuously. This salsa is excellent on tacos, eggs, grilled chicken, or mixed into rice and beans.',
};
