export const silkenTofuStew = {
  name: 'Silken Tofu Stew',
  param: 'silken-tofu-stew',
  recipeImage: 'assets/images/silken-tofu-stew.jpg',
  star: false,
  introText: 'A fiery, comforting Korean-style stew with silky soft tofu, vegetables, and a bold gochugaru broth.',
  description:
    'This vegan sundubu-jjigae is a spicy, deeply savory Korean stew built on a base of gochugaru, soy sauce, and sesame oil. Silken tofu breaks apart into the bubbling broth alongside mushrooms, zucchini, and scallions. Serve it in a hot stone bowl with rice for the full experience.',
  category: ['main', 'soup'],
  tags: {
    quick: true,
    easy: true,
    temperature: '',
    clean: true,
    cheap: true,
  },
  ingredients: [
    {
      name: 'Sesame oil',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: true,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Garlic',
      amount: 4,
      unit: 'cloves',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Gochugaru',
      amount: 2,
      unit: 'tbsp',
      flex: 'Gochujang or chili flakes',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Soy sauce',
      amount: 1,
      unit: 'tbsp',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Mushrooms',
      amount: 150,
      unit: 'g',
      flex: 'Shiitake, enoki, or oyster mushrooms',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Zucchini',
      amount: 1,
      unit: '',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Silken tofu',
      amount: 300,
      unit: 'g',
      flex: 'Soft tofu',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Vegetable broth',
      amount: 2,
      unit: 'cups',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Scallions',
      amount: 2,
      unit: '',
      flex: '',
      optional: false,
      topping: true,
      done: false,
    },
    {
      name: 'Sesame seeds',
      amount: 1,
      unit: 'tsp',
      flex: '',
      optional: true,
      topping: true,
      done: false,
    },
    {
      name: 'Sugar',
      amount: 1,
      unit: 'tbsp',
      flex: 'Any sweetener',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: [
    'Heat sesame oil in a pot or stone bowl over medium heat.',
    'Dice the onion and mince the garlic. Sauté until the onion is translucent, about 3 minutes.',
    'Add the gochugaru and stir for 30 seconds until fragrant.',
    'Slice the mushrooms and zucchini. Add them to the pot and cook for 2 minutes.',
    'Pour in the vegetable broth and soy sauce. Bring to a boil.',
    'Gently slide in the silken tofu in large pieces. Let it simmer for 8-10 minutes, breaking it up slightly with a spoon.',
    'Slice the scallions and scatter them on top along with sesame seeds.',
    'Serve immediately with steamed rice.',
  ],
};
