export const swedishBalls = {
  name: 'Swedish Balls',
  param: 'swedish-balls',
  recipeImage: 'assets/images/swedish-balls.jpg',
  star: true,
  introText: 'Delicious Swedish meatballs served with creamy gravy and lingonberry sauce.',
  description:
    "These Swedish meatballs are a comforting classic, featuring a rich and creamy gravy that's perfect for serving over mashed potatoes. The addition of lingonberry sauce adds a delightful tartness that balances the savory flavors.",
  category: 'main',
  tags: {
    quick: false,
    easy: false,
    temperature: null,
    clean: false,
    cheap: false,
  },
  ingredients: [
    {
      name: 'Soy mince',
      amount: 500,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Onion',
      amount: 1,
      unit: 'large',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Cream',
      amount: 200,
      unit: 'ml',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
    {
      name: 'Lingonberry jam',
      amount: 100,
      unit: 'g',
      flex: '',
      optional: false,
      topping: false,
      done: false,
    },
  ],
  instructions: ['Nothing yet.'],
  notes: 'MSG is amazing in this dish.',
};
